### ISSUE TITLE
[math] not rendering

### ISSUE THREAD

**Issue by boonebgorges** [livinglab/webwork-for-wordpress#1]
https://openlab.citytech.cuny.edu/groups/openlab-webwork-integration-project/forum/topic/setting-up-webwork-test-integration-with-openlabdev-org/#post-35041

**Comment by boonebgorges** [comment]
Andrew - Can you please share the URL of the problem where you initiated your question? TeX should, generally speaking, be parsed; but there may be something about the `[math]` markup in particular that's causing problems.

**Comment by drdrew42** [comment]
Set 3, problem 3 in WW-Dev

From the debug dump:
<span class="MathJax_Preview">[math]</span><script type="math/tex; mode=display">\frac{7}{3x+4}+\frac{32}{6x^{2}+5x-4} = \frac{x}{2x-1}.</script>

and 

Solutions (separate by commas): <span class="MathJax_Preview">[math]</span><script type="math/tex">x =</script> 

neither of these are rendering under "Show Problem" - all I see is [math] in their place.

**Comment by drdrew42** [comment]
LOL, trying to copy-paste HTML code. Let's try this again:

`<span class="MathJax_Preview">[math]</span><script type="math/tex; mode=display">\frac{7}{3x+4}+\frac{32}{6x^{2}+5x-4} = \frac{x}{2x-1}.</script>`

and 

`Solutions (separate by commas): <span class="MathJax_Preview">[math]</span><script type="math/tex">x =</script>`

**Comment by drdrew42** [comment]
Actually, I'm not getting the [math] to render anywhere...
Is it just me? I'm on Chrome Version 48.0.2564.109 (64-bit)

**Comment by boonebgorges** [comment]
It looks like `[math]` and `<script type="math/tex">` means that MathJax has *already* converted the content. I'll have to find a way to back-convert it, or to force MathJax to display it.

In my original development, TeX was being properly rendered, but it's possible it had originally been generated in a different way - using `$` or `\(` delimiters or something. Can you let me know how the TeX was originally written, when seeding the problem?

**Comment by drdrew42** [comment]
In WeBWorK, TeX is delimited by `\( ... \)` or `\[ ... \]`, but when it's appearing in the dump, there's no delimiters beyond the `<script>` tags. What appears between the `<script>` tags is legit TeX code for the original problem, just without any delimiters.

In the usual TeX files, math expressions are delimited with `$ ... $` or `$$ ... $$`

**Comment by drdrew42** [comment]
http://docs.mathjax.org/en/v1.1-latest/model.html

This document describes exactly what we're seeing. It looks like the submission of MathJax data is designed for use in an older version of MathJax (1.1), well behind the current v2.6

**Comment by boonebgorges** [comment]
Ah, interesting. What version of WeBWorK are you running?

**Comment by drdrew42** [comment]
2.11, I updated over the winter break.

**Comment by drdrew42** [comment]
I think I found the problem.
I see call to load the MathJax script in the header:
`<script type="text/javascript" src="/webwork2_files/mathjax/MathJax.js?config=TeX-MML-AM_HTMLorMML-full"></script>`
but I'm seeing an error from the JS Console in Chrome:
`http://openlabdev.org/webwork2_files/mathjax/MathJax.js?config=TeX-MML-AM_HTMLorMML-full`
**Failed to load resource: the server responded with a status of 404 (Not Found)**

Also, I was wrong earlier:
Reading through MathJax documentation, it looks like everything is correct for the current version.
`<script type="math/tex">TEX_STUFF</script>`
is the proper manner of calling MathJax to process TEX_STUFF, with the script tags as delimiters. And according to the documentation, the "MathJax_Preview" is placed in front of the script tags because of issues with IE handling the HTML codes in some weird way.

**Comment by drdrew42** [comment]
We don't necessarily need a local instance of MathJax (for now?)

Just replace the previous call to load MathJax.js with the following:
`<script type="text/javascript" async
  src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config= TeX-AMS-MML_HTMLorMML">
</script>`

**Comment by boonebgorges** [comment]
Yes, I'm already loading the script from the mathjax.org CDN, but there 
are other conflicts on the page, perhaps as a result of the fact that 
I'm dumping the contents of the original POST request onto the page. I 
will look into it.

**Comment by boonebgorges** [comment]
The underlying problem was the finickiness of how MathJax needs to be loaded. I was stripping the JS sent from WeBWorK, for security reasons, and attempting to load MathJax in the footer of the page. But it turns out that MathJax doesn't work if it's loaded outside of the document head. I'm now reproducing something close to what WW was sending over, and TeX is now being parsed as expected.
