### ISSUE TITLE
Another TeX rendering issue

### ISSUE THREAD

**Issue by drdrew42** [livinglab/webwork-for-wordpress#105]
Related to closed issue #84 

https://openlab.citytech.cuny.edu/ol-webwork/#:problemId=local/3x3-Systems/triangular.pg:questionId=667

In the LaTeX "array" environment, ampersands are used to delineate separate columns to ensure vertical alignment. It seems these ampersands are being interpolated into HTML before being sent over to OL?

Here is the offending TeX code from the WW problem:
`\begin{array}{rcl} [$LHS1] & = & [$RHS1] \\ [$LHS2] & = & [$RHS2] \\ [$LHS3] & = & [$RHS3] \end{array}`
(The array has three columns, aligned left/center/right, respectively - the ampersands separate the columns, while the double \\ separate the rows.)

Is there a way to recognize the use of this TeX environment and maintain the ampersands for rendering in-page?

**Comment by boonebgorges** [comment]
I think I've got this half-solved. Ampersands and array formatting should now be correctly interpreted. See https://openlab.citytech.cuny.edu/ol-webwork/#:problemId=local/3x3-Systems/triangular.pg:questionId=667 (be sure to do a hard refresh)

It appears that formatting of most user questions is correct:
![screenshot_2017-09-05_16-01-58](https://user-images.githubusercontent.com/246627/30083384-d72b8562-9253-11e7-9dc3-5a91114c477e.png)

In this specific case, the question that appears at the top of the page doesn't have right-hand values. It appears to be pulling from this specific question: https://openlab.citytech.cuny.edu/ol-webwork/#:problemId=local/3x3-Systems/triangular.pg:questionId=152 Is there a WeBWorK-related reason why the values would be empty in this case, or should I go digging?

**Comment by drdrew42** [comment]
I noticed that! It doesn't seem to be an issue with more recently submitted questions... whatever it _was_ seems to no longer be an issue. (All questions from this problem set have literally the exact same formatting here.)
