### ISSUE TITLE
Don't inherit 'course' and 'section' as fallback values on new questions

### ISSUE THREAD

**Issue by boonebgorges** [livinglab/webwork-for-wordpress#112]
See https://openlab.citytech.cuny.edu/groups/openlab-webwork-integration-project/forum/topic/possible-bug-2/ and especially https://openlab.citytech.cuny.edu/groups/openlab-webwork-integration-project/forum/topic/possible-bug-2/#post-47455 for background.

**Comment by boonebgorges** [comment]
I've made the change. Questions that are created directly through WW - ie, by browsing from the home page, clicking on a question, then scrolling to the top of the question page and posting a new item, rather than clicking 'Ask a Question' in WW - now have no `course` or `section` set.

**Comment by bree-z** [comment]
Sorry, I'm unsure where I should be posting a new item on WW-dev to test this.  @drdrew42 or @boonebgorges could you send a screenshot or URL, please?  Sorry if I'm being dense!  Thanks!

**Comment by drdrew42** [comment]
This is regarding the posting of questions without coming directly from WeBWorK? In other words, any questions _other than_ those that come from "ask for help"...

**Comment by boonebgorges** [comment]
@bree-z Not being dense! This is confusing. @drdrew42 is correct - this is for when you create a question via browsing through the OL site, as opposed to clicking 'Ask for Help'.

**Comment by bree-z** [comment]
Ok, great, thanks!  :)

This time I went to the OL-WW site and asked a question without going through WW-Dev.  It did not include any course/section information.

<img width="704" alt="screen shot 2018-05-25 at 6 48 31 pm" src="https://user-images.githubusercontent.com/7189824/40553814-773defc4-604c-11e8-8a4e-404e2afe904c.png">

**Comment by bree-z** [comment]
I think this one can be closed.
