### ISSUE TITLE
Improved sort for Section filter dropdown

### ISSUE THREAD

**Issue by boonebgorges** [livinglab/webwork-for-wordpress#113]
Should be sorted by:
1. Chronological DESC. Use FXX/SXX to determine dates.
2. Alphabetical ASC within a given term.

See https://openlab.citytech.cuny.edu/groups/openlab-webwork-integration-project/forum/topic/possible-bug-2/ for more background.

**Comment by drdrew42** [comment]
I have "testing" courses set up for Tyler and Bree, I may have to remind them of their logins and the URL for these hidden courses... but that's a way we can get multiple sections involved.

**Comment by boonebgorges** [comment]
Thanks, @drdrew42.

I've also attached a screenshot from my local if it helps.

![screenshot_2018-05-02_09-58-36](https://user-images.githubusercontent.com/246627/39531108-14cb5714-4df0-11e8-89a4-b1d8b7ce62f1.png)

**Comment by bree-z** [comment]
Hi @drdrew42 - 

I'm able to log in to WW-Dev, but I'm not sure how to find different courses.  If I click on Courses in the left sidebar nav it takes me to the list of actual live courses (http://mathww.citytech.cuny.edu/webwork2/).  Or is it easier to test on production after the release?

Thanks!

**Comment by drdrew42** [comment]
You have a separate course from long ago - it's unlisted on the public-facing "courses" page...

http://mathww.citytech.cuny.edu/webwork2/MAT9999-S17-Zuck

IIRC, your login and password are both 'bzuck'

**Comment by bree-z** [comment]
Thanks, @drdrew42 !

@boonebgorges , when I ask a question from MAT9999-S17-Zuck, the question appears on the OLdev WW site with the correct course/section information, but it doesn't appear in the dropdowns.   

<img width="1183" alt="filters" src="https://user-images.githubusercontent.com/7189824/40604723-b2d9feb0-6268-11e8-9d9f-4d1fd7c00f8a.png">

There are a few questions on the site now from the MAT9999-S17-Zuck, e.g.:

http://openlabdev.org/webwork-playground/#:problemId=local/HigherRoots/square-roots-with-negatives.pg:questionId=11910

and

http://openlabdev.org/webwork-playground/#:problemId=local/IntegerExponents/multiply-divide-easy.pg:questionId=11905

Thanks!

**Comment by bree-z** [comment]
This is populating correctly now, thanks!  I can't test the chronological descending section order, but all other filter functionality is working.  I've made a note to be sure to check this out in post-release testing.
