### ISSUE TITLE
Design updates

### ISSUE THREAD

**Issue by boonebgorges** [livinglab/webwork-for-wordpress#114]
See https://www.dropbox.com/sh/ibelqxkpebe7xl1/AACVt7wutZE7O5f_yzPzlZkxa?dl=0

**Comment by boonebgorges** [comment]
I've made these changes, but it might be best to hold off on testing them until after a review of #109.

**Comment by jennaspevack** [comment]
@boonebgorges, not sure if these css updates will address this, but it appears that the site logo on Production is cut off.  And it also looks like there are some CSS conflicts (?) with the WP Navbar - ie: the spacing between menu items in the dropdowns are off. 
https://www.dropbox.com/s/l6lz7q2y4nvu9wz/cssconflictswithWPnav.png?dl=0

**Comment by boonebgorges** [comment]
Yes, I'd noticed this, Jenna.

I did fix the header issue as part of the changes in this ticket. From what I can tell, it was due to an update in the Hemingway parent theme. I just put that small fix onto the production site so that you can see it in action.

The issues with the adminbar seem more complicated. I believe it's probably a more general problem than ol-webwork - it seems like the styling in themes is overriding the not-specific-enough network toolbar styling. I've opened a ticket on OpenLab for it. http://redmine.citytech.cuny.edu/issues/2302

**Comment by jennaspevack** [comment]
Okay, thanks!

**Comment by moui72** [comment]
as far as I can tell, the issues with design seem resolved -- is there any specific testing that needs to be done?

**Comment by boonebgorges** [comment]
As long Bree and Tyler are happy with things here, I think we can safely close. Thank you!
