### ISSUE TITLE
Discourage question posting without "What I've Tried"

### ISSUE THREAD

**Issue by boonebgorges** [livinglab/webwork-for-wordpress#117]
We want to discourage posting new questions without having filled in the "what I've tried" field. Here's the proposal:

1. If you fill in a question but `tried` is empty, and you click Submit:
    - the question will not be submitted
    - a message will appear, perhaps just above the Submit button, along the lines of "You haven't described what you've tried ... did you know you can take a picture of your work and upload it" or something like that
    - Perhaps we also want a visual change to the Submit button to show that we're in this interstitial space

2. If you click Submit while the nudge is showing, the question submission process will be allowed to proceed.

3. It's technically possible to remove the nudge and/or the alternative Submit button styling once the user starts typing in the Tried field, but I'd suggest that this may be a little jarring, and we should just leave it in place once it's been shown (since we allow submission at this point anyway; see 2)

@jennaspevack and @drdrew42 will review the above, and @jennaspevack will provide a mockup of this flow.

**Comment by drdrew42** [comment]
Proposed "nudge" message:

> "We will be better able to help you with this problem if we can see what you've already tried. Did you know that you can upload a photo of your work?"

Is 1st person plural an acceptable voice? ;P

**Comment by jennaspevack** [comment]
@boonebgorges, here's a mockup with suggested visuals for this flow.  See item 1. 
https://www.dropbox.com/s/e8i2ricwn16o7xt/OLWW_LAYOUT_PROBLEMPOSTV6.png?dl=0

@drdrew42, The message is a bit long. Does something like this work? 'You haven't described what you've tried. Did you know you can upload an image of your work?' It would be good to keep it short to keep the same font size as the Submitted question message.

**Comment by jennaspevack** [comment]
Looks good. 

The hover state for the submit button in "interstitial space" wasn't added, but maybe that's because I put a ? next to it. :) 

I was able to submit a question without adding any content in either boxes. Should we be preventing that? 
http://openlabdev.org/webwork-playground/#:problemId=local/ShiftingParabolas/shift-down.pg:questionId=11697

**Comment by boonebgorges** [comment]
> The hover state for the submit button in "interstitial space" wasn't added, but maybe that's because I put a ? next to it. :)

Whoops, no, I just didn't understand what you'd written :) I've added the styling.

> I was able to submit a question without adding any content in either boxes. Should we be preventing that?

Perhaps, though is this an actual problem? It makes the logic a lot more complicated. If we decide we need to fix this now, we'll need a new description of the flow. Maybe we could use the "error" space ("You haven't described...") but show different text, and then presumably we would *not* allow 'Submit' to be clicked if 'Question' was empty. Schematically:

```
User clicks Submit. Three possible cases:
    1. "question" is empty (ignore "tried"). Show "You must provide a question..." error, don't allow Submit.
    2. "question" is non-empty, but "tried" is empty. Show "You haven't described..." error, but allow Submit.
    3. Both fields are filled. Allow submit.
```

We'd also need to decide whether we want the same styling for "question-is-empty" (a blocking error condition) and "tried-is-empty" (a non-blocking error condition).

**Comment by bree-z** [comment]
Functionality is working as expected, and the UI matches the comps.  

As for blocking users from submitting an empty question, I think ideally we might want to do that, but if it's not something that students are doing, perhaps it can wait?

**Comment by boonebgorges** [comment]
My recollection of the functionality conversation was that we were going to ease into this feature for the time being - nudging but not forcing. As such, I'm tentatively closing this ticket, with a note for @drdrew42 and others that we should assess after the next term whether the nudge is sufficient, or whether we should be more forceful.
