### ISSUE TITLE
Discourage/prevent image insertion without alt text

### ISSUE THREAD

**Issue by boonebgorges** [livinglab/webwork-for-wordpress#118]
Previously: #107

**Comment by boonebgorges** [comment]
This turns out to be a moderately difficult technical task. I've attached a gif of a first pass at an error workflow. If we think that some version of this is worth doing, the next step is likely for @jennaspevack to make some suggestions about better styling/wording.

![peek 2018-05-01 14-05](https://user-images.githubusercontent.com/246627/39488917-6d8a2544-4d49-11e8-86bb-b722ae6f7f88.gif)

**Comment by boonebgorges** [comment]
(I've pulled the changes to the webwork-playground environment so that you can test in a live environment if that's easier.)

**Comment by bree-z** [comment]
Functionality is working well.  Does this still need design input from @jennaspevack ?  Thanks!

**Comment by boonebgorges** [comment]
It would be nice to get thoughts from @jennaspevack, even if it's just "that looks good" - the main reason being that we may want to adapt this change for the OpenLab more generally at some point. (The main design points are: 1. the wording, styling, placement of the 'You must supply...' message, and 2. the red outline on the 'Alt Text' input field.)

"Looks good for OL-WW, may need more revision for OL" is a perfectly good answer for now!

**Comment by jennaspevack** [comment]
Looks great! Sorry for the delay.

**Comment by boonebgorges** [comment]
Great, thanks! There may still be some weirdness on mobile, but we are addressing in #122, so I think this can be closed.
