### ISSUE TITLE
Hover states

### ISSUE THREAD

**Issue by jennaspevack** [livinglab/webwork-for-wordpress#120]
@boonebgorges, sorry these were left out of the original mockup. Fine to move for future release, but thought I'd add them here, just in case. See item 3.
https://www.dropbox.com/s/e8i2ricwn16o7xt/OLWW_LAYOUT_PROBLEMPOSTV6.png?dl=0

**Comment by boonebgorges** [comment]
No problem, @jennaspevack. I've added them as part of 2b9a895; see #117.

**Comment by jennaspevack** [comment]
Okay, thanks!

**Comment by bree-z** [comment]
This looks good!
