### ISSUE TITLE
Preview link misaligned on mobile

### ISSUE THREAD

**Issue by bree-z** [livinglab/webwork-for-wordpress#123]
On mobile, the 'Preview' link for a question/response overlaps with the text box field.  Also, the 'Add Images' link overlaps with the "Describe what you have tried" text.

![previewlinkmobile](https://user-images.githubusercontent.com/7189824/40727415-82a6e3e2-6430-11e8-93a5-dfec5e096ff7.jpg)

![img_7150](https://user-images.githubusercontent.com/7189824/40727566-d086f99e-6430-11e8-96f3-8cf661149968.PNG)

**Comment by bree-z** [comment]
iPhone 7, iOS 11.3.1

**Comment by boonebgorges** [comment]
Thanks, Bree. I've just pushed up a suggested fix. See screenshots (<500px only; wide screens remain the same). @jennaspevack Does this look acceptable for now, or do you want to have a go at it?

![screenshot_2018-05-30_10-16-39](https://user-images.githubusercontent.com/246627/40729746-b5eb1252-63f2-11e8-88ec-fdc6d5f12e67.png)
![screenshot_2018-05-30_10-16-29](https://user-images.githubusercontent.com/246627/40729747-b602e3a0-63f2-11e8-9895-5d3548a20490.png)

**Comment by bree-z** [comment]
This looks good to me, but I won't close this in case @jennaspevack wants to take a look.

**Comment by boonebgorges** [comment]
:+1:
