### ISSUE TITLE
Banner overflow on mobile view

### ISSUE THREAD

**Issue by moui72** [livinglab/webwork-for-wordpress#124]
At view widths < ~580px the banner begins to slightly overflow the viewport.

![screenshot_2018-05-30-15-39-32_20180530154536](https://user-images.githubusercontent.com/3885628/40743904-d6e27e22-6420-11e8-8570-c1c109bd2a00.jpg)

**Comment by boonebgorges** [comment]
Thanks for the screenshot. I don't know that I have comps for what this ought to look like. I've added some styles so that the header shrinks at smaller sizes.

![screenshot_2018-05-31_08-41-05](https://user-images.githubusercontent.com/246627/40785570-6b450782-64ae-11e8-86c1-e7406d067caf.png)

**Comment by moui72** [comment]
I think this looks good. @jennaspevack want to have a say before I close?

**Comment by boonebgorges** [comment]
Thanks, gang :)
