### ISSUE TITLE
Header elements in problem source are being rendered as yellow text

### ISSUE THREAD

**Issue by boonebgorges** [livinglab/webwork-for-wordpress#129]
See https://i.imgur.com/myTtQXt.png and http://mathww.citytech.cuny.edu/webwork2/MAT1375/Functions_-_Difference_Quotient/1/?user=bgorges&effectiveUser=bgorges&key=9lp4eIQHT6IT8iv6gLYYC6h4A0QyJnTs

The issue appears to be an overapplication of the `.canopen` styling. See #32 89aa6239bc7524e2dc65e0360f9d15dc776324d5 The `h3` selector here is too broad https://github.com/livinglab/webwork-for-wordpress/blob/423ccb17ec6bfddfb0b130fc657adc96832027af/assets/js/webwork-scaffold.js#L49. We'll have to go back and find a more precise way of figuring out when a problem contains "scaffolding" markup. @drdrew42 If you have any ideas off the top of your head about how the latter might be done, any suggestions would be great.

**Comment by drdrew42** [comment]
What does OL see in the post data with regards to problems that contain "scaffolding"?

We started using header styling within problems (to distinguish the expository content from the practice content), so is that what's causing the h3 collision in the logic?

**Comment by boonebgorges** [comment]
It looks to me like sections of scaffolded problems start like this:

```html
<div class="section-div"><h3 id="Prob-1_SC-1_SECT-3" class="iscorrect">Step 3: Complete the Square</h3>
```

So perhaps the "scaffolding" styling should apply only to those items that appear inside of `.section-div`. Does this seem accurate to you? Do you build the scaffolded markup by hand, or does WeBWorK do it for you?

**Comment by drdrew42** [comment]
WeBWorK does indeed handle the styling. Within the PG markup, we have `Scaffold::Begin()` and `Section::Begin("title")` - it would make sense that each section of the scaffold have its own div class.

**Comment by boonebgorges** [comment]
Sounds good. We'll go with the `section-div` sniff, then. But we should keep in mind that this is the sort of thing that is subject to breakage if the WW devs decide to change the markup.

**Comment by boonebgorges** [comment]
@drdrew42 I believe I have a fix for this in place, but I won't be able to test fully until the WW-Dev course is populated with the necessary content. When you've got a chance, would you mind loading (a meaningful subset of) the new 1275 and 1375 content into WW-Dev?

**Comment by drdrew42** [comment]
Do you mean a problem set that contains instances of Header + Scaffolding in the same problem?

**Comment by boonebgorges** [comment]
If that sort of thing might occur in the real world, then yes. Mainly I just mean: can we have the content from http://mathww.citytech.cuny.edu/webwork2/MAT1375/Functions_-_Difference_Quotient/1/ and the rest of that course put into WW-Dev, so that we'll have a complete-ish set to work with.

**Comment by drdrew42** [comment]
I've imported the Functions - Difference Quotient set into the WW-Dev (for testing of tables)
And also Polynomials - Inequalities (for testing of scaffolding), and Polynomials - Division (for tables, scaffolding, and headers)

**Comment by boonebgorges** [comment]
Excellent, thanks!

**Comment by boonebgorges** [comment]
I've made the changes. Headers within the problem text are now rendered as in the screenshot:

![screenshot_2018-09-25_14-12-07](https://user-images.githubusercontent.com/246627/46037177-0df83880-c0cd-11e8-8381-9691e5ddafba.png)

It seems to me that these longer problems (especially those with internal formatting) mean that we should no longer be boldfacing all text in the problem summaries, so I've gone ahead and done that, though the decision probably needs design signoff.

**Comment by bree-z** [comment]
Hi Boone, 

I still see the yellow headers, e.g. here:

WW: http://mathww.citytech.cuny.edu/webwork2/WW-Dev/Polynomials_-_Inequalities/1/?user=student1&key=VYKlNLYNiiOn8eSkR5GcGwItwPMTjs52&effectiveUser=student1
OL-WW: http://openlabdev.org/webwork-playground/#:problemId=local2/setPolynomials_-_Inequalities/intro-poly-ineq.pg 

![yellowheaders](https://user-images.githubusercontent.com/7189824/51555209-2131cf80-1e45-11e9-8f32-e4e262370124.png)

**Comment by boonebgorges** [comment]
I believe that those specific headers ("Identify roots" etc) are *supposed* to be rendered in yellow, because they are clickable accordions ("scaffolded problems"). Can you confirm @drdrew42 ?

**Comment by drdrew42** [comment]
Oh yes, those are supposed to be yellow, they are collapsible parts of the problem.

**Comment by bree-z** [comment]
Thanks, @drdrew42 .  We can close this one.
