### ISSUE TITLE
List elements in problem summary should have styled bullets

### ISSUE THREAD

**Issue by boonebgorges** [livinglab/webwork-for-wordpress#130]
See https://i.imgur.com/yjU5Z3V.png Looks like this is just part of the Hemingway reset styles, so we should be able to override easily.

**Comment by boonebgorges** [comment]
This should now be resolved. See http://openlabdev.org/webwork-playground/#:problemId=local2/setDifference_Quotient/intro-diff-quot.pg

**Comment by bree-z** [comment]
This looks good to me, thanks!
