### ISSUE TITLE
Many linebreaks are being inserted before PGML-formatted tables

### ISSUE THREAD

**Issue by boonebgorges** [livinglab/webwork-for-wordpress#131]
See https://i.imgur.com/1nPNtUB.png

There are many `<br>` elements in the rendered source, so I'm guessing that this is related to #82. The application is supposed to strip duplicate `<br>` but there must be something weird happening in this case.

**Comment by boonebgorges** [comment]
I think it's a good idea in general to standardize on a technique for creating tables (and other bits of "specialty" markup), if only to preserve our collective sanity when we try to parse and style it on the OL-WW end.

As for this specific issue, it seems to be a bug in webwork-for-wordpress that so many line breaks would be allowed in the content at all, so it's worth looking at in more detail regardless of whether we abandon the specific table markup.

**Comment by drdrew42** [comment]
I'll work on revising the table, but I will wait to implement until we've done some further testing, then?

**Comment by boonebgorges** [comment]
Yes, please leave this specific example in place so that I can do the necessary debugging. But you should feel free to go ahead and start researching a general approach for tables.

**Comment by boonebgorges** [comment]
Eesh, this turned out to be a difficult one to diagnose. It turns out that the original markup had some line breaks between table elements, eg:

`<table><tr><td>foo</td>
</tr><tr>...`

My linebreak-converting script was catching these linebreaks and converting them to `<br />` tags. On render, the browser was rejecting `<br />` elements inside of `<tables>`, and rendering them instead just before the `table`.

I added some parsing that eliminates all non-content-related line breaks inside of `table` elements, and it seems to have fixed the problem. See http://openlabdev.org/webwork-playground/#:problemId=local2/setDifference_Quotient/intro-diff-quot.pg

**Comment by bree-z** [comment]
This seems fine, but just going to give it one more check to be sure!

**Comment by bree-z** [comment]
This looks good to me.
