### ISSUE TITLE
Tables in problem summary are poorly formatted

### ISSUE THREAD

**Issue by boonebgorges** [livinglab/webwork-for-wordpress#132]
We should try to mimic table formatting - outline, padding, alignment, etc - from WeBWorK.

OL:
![tf1ljy0](https://user-images.githubusercontent.com/246627/45316312-5ecc3680-b4fc-11e8-9865-7e6235e35096.png)

WeBWorK:
![screenshot_2018-09-10_13-20-34](https://user-images.githubusercontent.com/246627/45316303-5673fb80-b4fc-11e8-90e1-353572e89501.png)

**Comment by boonebgorges** [comment]
Notwithstanding #133, this should mostly be fixed. See http://openlabdev.org/webwork-playground/?post_data_key=webwork_post_data_85b1da6c5d4e38c8963487611d7e21f7#:problemId=local2/setDifference_Quotient/intro-diff-quot.pg

**Comment by bree-z** [comment]
Table formatting looks good to me, for the most part.  The only issue I'm seeing is that depending on the problem, some tables are cut off on the right side, when I click "View my problem" to expand the problem text.  E.g.: http://openlabdev.org/webwork-playground/#:problemId=local2/setDifference_Quotient/diff-quot-quad.pg:questionId=11803  Though I'm guessing this is related to #134 ?

![wwoltablecutoff](https://user-images.githubusercontent.com/7189824/51505374-209d2880-1db4-11e9-9085-e4ef2e5c7071.png)

If I scroll to the top of a problem page, I can see the whole table but it spills outside the field, as described in #134 

![screen shot 2019-01-21 at 7 44 03 pm](https://user-images.githubusercontent.com/7189824/51505528-f304af00-1db4-11e9-9c1d-b89f54904dcc.png)

For other problems, the table isn't cut off when viewing a problem.  E.g.: http://openlabdev.org/webwork-playground/#:problemId=local2/setDifference_Quotient/diff-quot-rational.pg:questionId=11801

![screen shot 2019-01-21 at 7 40 04 pm](https://user-images.githubusercontent.com/7189824/51505437-6659f100-1db4-11e9-85bf-374387582cfc.png)

**Comment by boonebgorges** [comment]
Thanks, Bree! You're correct that the table-formatting parts are what's being discussed in #134. You're it only on certain problems because only a subset of the source problems are wide enough to trigger the problem. I think there's a general consensus on #134 that this is an issue that should mostly be resolved at the editorial level.

Since other issues are looking OK, let's close this ticket.
