### ISSUE TITLE
Emoji font from wordpress.org can override MathJax

### ISSUE THREAD

**Issue by boonebgorges** [livinglab/webwork-for-wordpress#135]
On Mac (tested in Safari and Firefox, though I think it's an OS issue), WP's emoji fallbacks are being used in at least some cases instead of those that ought to be provided by MathJax. See the two screenshots:

<img width="1381" alt="emoji" src="https://user-images.githubusercontent.com/246627/45447076-12c8ef80-b6be-11e8-8231-9babde238355.png">

![screenshot_2018-09-12_19-00-37](https://user-images.githubusercontent.com/246627/45447099-283e1980-b6be-11e8-8747-c8881cb38c56.png)

I'm unsure whether this is a problem with MathJax improperly detecting native emoji support, which prompts WP's emoji fallback, which in turn gives the wrong svg; or whether WP is somehow stomping on MathJax.

**Comment by boonebgorges** [comment]
I disabled WordPress's emoji polyfill script on the webwork-theme, and it seems to do the trick. This is ready for a test.

**Comment by drdrew42** [comment]
I still see the grey emoji square in Chrome 70.0.3538.110 (Official Build) (64-bit)

**Comment by boonebgorges** [comment]
Where do you see it? I haven't pushed to the production site.

**Comment by bree-z** [comment]
I think this looks good.  I’m adding screenshots just in case I misunderstood what I’m looking for.  I see the same square box I saw on the OL side as on WW, and when I inspect element I don’t see any reference to an emoji img class.

Thanks!

![noemoji](https://user-images.githubusercontent.com/7189824/51505297-bf755500-1db3-11e9-800c-4ace82b854d4.png)

![noemojiinspect](https://user-images.githubusercontent.com/7189824/51505298-bf755500-1db3-11e9-9093-c44f51606d27.png)

**Comment by boonebgorges** [comment]
Yup, this looks good. Thank you, Bree!
