### ISSUE TITLE
Custom message on wp-login.php when redirected there from WW

### ISSUE THREAD

**Issue by boonebgorges** [livinglab/webwork-for-wordpress#141]
When an 'Ask for Help' request comes from WW, we redirect it to wp-login.php if the user is unauthenticated.

This redirect should include a special param (say, `?is-webwork-redirect` or whatever), and when that param is detected, we ought to show a special login message. I think the generic message should be something like: `You have been directed to %s from WeBWorK. Before posting a question, you must log in using your %s credentials`, where `%s` is the name of the site (in the case of the OL it would be `WeBWorK on the OpenLab`).

I'll put a filter on this so that it can be modified. I assume we want something a bit more tailored for the OL, like `You must log into the OpenLab to post a WeBWorK question.` Other suggestions on wording are welcome.

**Comment by boonebgorges** [comment]
I've made the change. Here's what it looks like out of the box:

![screenshot_2018-12-20_14-43-35](https://user-images.githubusercontent.com/246627/50310115-a3a22a80-0466-11e9-90b9-b62722dc5704.png)

I customized the text for the OpenLab as follows:

![screenshot_2018-12-20_14-46-21](https://user-images.githubusercontent.com/246627/50310122-a9980b80-0466-11e9-804f-facfb3987b5a.png)

Happy to change the wording in either case.

**Comment by bree-z** [comment]
This looks good, thanks!
