### ISSUE TITLE
WeBWorK not sending problem information

### ISSUE THREAD

**Issue by bree-z** [livinglab/webwork-for-wordpress#142]
When I click 'Ask a Question' on a WeBWorK problem page, there's no user or question information being sent to the openlabdev.org WW site:

- In WW-Dev, I click 'Ask for Help', e.g.: http://mathww.citytech.cuny.edu/webwork2/WW-Dev/Functions_-_Difference_Quotient/1/?key=P0EiUosT6GQR2u1dUjOc5tRVxI4h439d&user=student1&effectiveUser=student1
- If I'm already logged in, I go directly to the openlabdev.org WW site, but just to the homepage: http://openlabdev.org/webwork-playground
- If I'm not logged into OL dev, I'm asked to log in and end up on http://openlabdev.org/webwork-playground

I tested on Chrome and Firefox and got the same result.

Thanks!

**Comment by boonebgorges** [comment]
Thanks, @bree-z. This appears to be a recurrence of https://github.com/livinglab/webwork-for-wordpress/issues/43, where the "library ID" is not appearing for students, and so WW-OL is unable to detect which problem to direct to.

@drdrew42 Could you please have a look and ensure that the configuration is set properly on WW-Dev, in addition to the production instances of WW?

**Comment by drdrew42** [comment]
I’ve updated the course config to display the problem library ID - but it doesn’t seem to fix the behavior when clicking “Ask for Help...

**Comment by bree-z** [comment]
Thanks, @drdrew42 and @boonebgorges !  Problems are now loading for me on OL-WW after clicking Ask for Help.
