### ISSUE TITLE
Course and Section information missing for student-posted questions

### ISSUE THREAD

**Issue by bree-z** [livinglab/webwork-for-wordpress#145]
Hi Boone, 

I vaguely remember this coming up last release but couldn't find a ticket.  When I ask a question on OL-WW as a student user, the metadata at the bottom of the problem that should display the question, course number, and section (e.g. IntegerExponents | MAT9999 | MAT9999-S17-Zuck) is missing the course number and section.  When I post as a faculty user (site admin) it appears.  

I tested in two different courses as faculty and student user, and it appears to be the user rather than the course.  I also noticed that the correct information shows on questions you posted.

Thanks!
![missingcourseinfo](https://user-images.githubusercontent.com/7189824/51627210-6b7f8300-1f0f-11e9-9833-0125f8b01dd5.png)

**Comment by boonebgorges** [comment]
I can't reproduce. Are you using a private browsing window? https://github.com/livinglab/webwork-for-wordpress/issues/111#issuecomment-393558527

**Comment by bree-z** [comment]
Aha, yes, thanks!  Now I remember this.  And yes, I was using a private browsing window.  When I don't, all course information appears as it should.

Sorry for the false alarm!
