### ISSUE TITLE
Replace progress indicators with reply count in accordion headers

### ISSUE THREAD

**Issue by boonebgorges** [livinglab/webwork-for-wordpress#146]
Reference: https://www.dropbox.com/s/enr47xuwh1rsico/Screenshot%202019-03-21%2015.32.04.png?dl=0

**Comment by boonebgorges** [comment]
@jennaspevack The Dropbox file ("Jenna's Mockup") is no longer there. (Maybe they didn't like that I linked to it in a GitHub issue?) Would you mind reposting and sending me a link?

**Comment by jennaspevack** [comment]
I think it's this one:
https://www.dropbox.com/s/m0iku851nka9ks3/OLWW-updates-JS.png?dl=0
<img width="740" alt="OLWW-updates-JS" src="https://user-images.githubusercontent.com/22797200/56761141-e26c2800-6759-11e9-941c-4c411e88883c.png">

**Comment by bree-z** [comment]
This looks good, thanks!
