### ISSUE TITLE
Change question accordion toggle icon

### ISSUE THREAD

**Issue by boonebgorges** [livinglab/webwork-for-wordpress#148]
On question lists, the accordion toggle icon should be https://fontawesome.com/icons/angle-up?style=solid and https://fontawesome.com/icons/angle-down?style=solid, instead of the current `+` and `-`.

**Comment by boonebgorges** [comment]
I've made the change but I need to have another look at the mockup to double-check the styling before it's ready to verify.

**Comment by boonebgorges** [comment]
Looks like it's not fully indicated in the mockups just how it should look - here are screenshots of what I've built. Let me know if this is what you had in mind. (cc @jennaspevack - see the icons in the upper right)

![Screenshot_2019-04-29_13-56-59](https://user-images.githubusercontent.com/246627/56919635-b832a700-6a86-11e9-84fa-0e5df138cfcf.png)
![Screenshot_2019-04-29_13-56-38](https://user-images.githubusercontent.com/246627/56919636-b832a700-6a86-11e9-821c-be3e7697d40e.png)

**Comment by jennaspevack** [comment]
Looks good to me!

**Comment by boonebgorges** [comment]
Awesome, thanks!
