### ISSUE TITLE
Add "respond to this question" link to questions in question list

### ISSUE THREAD

**Issue by boonebgorges** [livinglab/webwork-for-wordpress#150]
See https://www.dropbox.com/s/enr47xuwh1rsico/Screenshot%202019-03-21%2015.32.04.png?dl=0

> Add a separate “Respond to this Question” link on the question card to clarify the distinction between viewing a list of questions, where users can’t reply vs. viewing a particular question, where there’s a clear method to reply.

On single-problem pages, this link should be shown only to logged-out users, and should link to the login page (returning to the question after login):

> Add link that is visible to all non-logged in users: “Respond to this Question” .  Clicking the link takes user to login page, and after login they return to the problem page.

On single-problem pages, logged-in users presumably don't need to see it. (This could use confirmation from @jennaspevack or @bree-z )

On the question list, all users see the link. Logged-out users are run through the login flow, while logged-in users are led directly to the question permalink.

**Comment by boonebgorges** [comment]
A first-pass implementation is ready to test. Four cases:

a. List view, non-authenticated: The Respond link leads to the login page, and after login, you're led to the question in Single view.
b. List view, authenticated: The Respond link leads to the question in Single view.
c. Single view, non-authenticated: Same as (a).
d. Single view, authenticated: There's already a Reply link here that just scrolls the page. This has been untouched.

**Comment by jennaspevack** [comment]
This seems fine to me, but @bree-z can you review to confirm?

**Comment by bree-z** [comment]
Yes, this looks good to me, thanks!  I'm going to leave this open though until I can run through all the tickets and make sure I've updated our testing spreadsheet.

**Comment by bree-z** [comment]
This is ready to close.
