### ISSUE TITLE
Ability to post question anonymously

### ISSUE THREAD

**Issue by boonebgorges** [livinglab/webwork-for-wordpress#151]
> Allow students to post their questions anonymously by adding checkbox and text: “Post this question anonymously. Only your professor will see your name.”
> a. The student’s name will be communicated to faculty in the email notification they receive from OL-WW when a student posts a question. 

> When students choose to post anonymously (see B1 below) Change question title text (A Question from…) to: “Question from a Student”

**Comment by boonebgorges** [comment]
I've just pushed a first version of this to openlabdev.org. Here's a brief gif:

![Peek 2019-04-29 12-58](https://user-images.githubusercontent.com/246627/56916527-b1079b00-6a7e-11e9-9cdf-4f2d0eb1fa33.gif)

A few assumptions and questions:

1. I assume we want this box *unchecked* by default.
2. The "Question from a Student" text is the only indication that a question is anonymous. There's no way for instructors to see the user's actual name, except by looking at the text of the email notification. IMO it would be nice to show this text to instructors, but (a) we don't have fine-grained control that allows us to show the name only the *specific* instructor for the section, and (b) showing the name without also indicating to the instructor that the question is anonymous (for other students) feels like a recipe for confusion. So it might be worth some additional UI here - maybe anon questions should show the regular "A question from Foo Bar" when viewed by instructors, but there should be a special visual indicator that it's an anonymous question, with some helpful hover text. Or perhaps the generic "Question from a student" text could be kept, but instructors will see an additional bit of UI that shows the user's real name, either statically or on hover/click.

**Comment by boonebgorges** [comment]
Another item to add to my list:

3. The 'anonymous' flag applies only for questions. If a faculty member responds, and then the author responds to that response, the response will not be anonymous. Should it be? Perhaps the author's responses should automatically be anonymous when on their own anonymous thread? A manual toggle for anonymous responses seems both cumbersome and likely to lead to bad behavior.

**Comment by jennaspevack** [comment]
1. Yes.

2. How about "Question from a student" text is kept, and the word "student" gets a tooltip with the student's name or the real name just replaces the student text on-focus/on-click?

Maybe use _text-decoration: underline #0043af dotted_ or similar to indicate tooltip/hover?

Not sure if this is what you had in mind...

3. I think if a student posts a question as anonymous all replies should be the same.

**Comment by boonebgorges** [comment]
> Maybe use text-decoration: underline #0043af dotted or similar to indicate tooltip/hover?

Sounds good. I'll work on this next week.

> I think if a student posts a question as anonymous all replies should be the same.

*All* replies? Or *all student* replies? Or *all replies by the original question author*? The latter seems "correct" to me - and maybe the reply title can be something like "Question Author" or something like that, in place of where the user name would be? See screenshot for a reminder of how the reply author names appear.

![Screenshot_2019-04-30_13-09-08](https://user-images.githubusercontent.com/246627/56983406-2d66b080-6b49-11e9-8e47-ed216e16ecc2.png)

**Comment by jennaspevack** [comment]
Yes, all replies from the anonymous student who originally posted the question. 

Just to clarify I'm assuming that if another student replies to a question they don't have the option of posting anonymously. My understanding was that it was just for questions.

"Question Author" sounds good.

**Comment by boonebgorges** [comment]
All sounds good. Thanks for confirming!

**Comment by boonebgorges** [comment]
Here's a first pass at the hover tooltip. Visible only to instructors/admins:
![Peek 2019-05-01 14-33](https://user-images.githubusercontent.com/246627/57037940-2e1d4680-6c1e-11e9-9828-010b852d5122.gif)

It's better to make the entire string hover-able, for translation reasons. Note that I'm using the same tooltip styling/behavior as the "Join / login to like" tooltip. @jennaspevack If you're happy with the way this looks, I'll apply it to anonymous replies as well.

**Comment by boonebgorges** [comment]
The 'Question Author' functionality has now been implemented. (That is: in a thread of replies to an anonymous question, replies written by the original question author have the title 'Question Author' rather than the user's name.) I went ahead and implemented the "real name" tooltip for this as well, though it can easily be changed if we decide we'd like a different UI.

**Comment by bree-z** [comment]
Thanks, Boone!  This is working as expected and the tooltip looks good to me!  

@jennaspevack not sure if you want to take a look at the tooltip, but otherwise we can close this, thanks!

**Comment by jennaspevack** [comment]
Thanks Boone!

The tooltip background color doesn't pass WAVE. Could we change that tooltip box .__react_component_tooltip.type-info to background-color: #c4c4c4 and text color: #000? 

And also the little triangle, .__react_component_tooltip.type-info.place-top:after border-top-color: #c4c4c4?

Example: https://www.dropbox.com/s/9qboats98ra0dlt/anonomous-hover.png?dl=0

I noted an issue with the anonymous link style here:
https://github.com/livinglab/webwork-for-wordpress/issues/149

**Comment by boonebgorges** [comment]
Sure thing. I've made the change.

**Comment by bree-z** [comment]
Thanks, Boone and Jenna!

This looks good to me.  When I inspect the element I see:

.__react_component_tooltip.type-info {
    background-color: #c4c4c4;
    color: #000;
}

I'm not sure where to find react_component_tooltip.type-info.place-top:after border-top-color but the little triangle appears to be the same background color, and I don't see any WAVE contrast errors.

Boone or Jenna, I'll let you decide if that's good enough to close.  Thanks!  :)

**Comment by jennaspevack** [comment]
Perfect. Thanks!
