### ISSUE TITLE
Remove "answered" functionality

### ISSUE THREAD

**Issue by boonebgorges** [livinglab/webwork-for-wordpress#154]
> Remove “This response answered my question” checkbox.

**Comment by boonebgorges** [comment]
Removing this bit of UI means that the "Answered" functionality is basically deprecated. This affects a number of places in the UI:

1. The Select Questions dropdown on the sidebar filters has options exclusively related to 'answered' state. Should it be removed altogether? This would also mean rephrasing the help text just above the filters ("use the filters below" and the linked help documentation).
2. On single problem pages, the info subheader under the problem title has text like `X QUESTIONS / Y RESPONSES / Z UNANSWERED`. Presumably we should remove the third part of this?

cc @jennaspevack @bree-z

**Comment by jennaspevack** [comment]
1. Yes. Seems like it would make sense to remove that filter altogether.
Filter copy suggestion: "You can select questions by course, section, or a specific WeBWorK problem set."
Help: seems like we can just remove the section "Answered and unanswered questions" but there are other references to Answered/Unanswered in Help. @bree-z is that something you are working on? If not, I'm happy to.

2. Yes. I think removing / Z UNANSWERED also makes sense.

**Comment by boonebgorges** [comment]
Thank you! I've merged the changes and it's ready to test.

**Comment by bree-z** [comment]
This looks good, thanks!  

I'll take care of the Help.  @jennaspevack I think you're right that we can remove the section "Answered and unanswered questions."  I'll also remove the references on the rest of that page, and on the Ask Questions page.
