### ISSUE TITLE
Instructor email notification should link to login page

### ISSUE THREAD

**Issue by boonebgorges** [livinglab/webwork-for-wordpress#157]
> Direct faculty to log into OL-WW after clicking on a link in an email notification about a question posted on the site.  This would be similar to how students are currently prompted to log in after clicking “Ask for Help” on WW.
> a. This would solve the following problem: Since faculty are not immediately prompted to login after being linked to a question, they aren’t always logged in when trying to answer a question and thus get confused about how to respond.  When they do log in, they’re taken back to the homepage and get confused about where they are.

**Comment by bree-z** [comment]
I've tested this as an instructor by subscribing to a question, and it's working as expected. When I click on the link in that email notification, I'm promoted to log in, if I'm not already authenticated.  But, I don't get the initial instructor notification that there's a new student question on OL-WW.  If I remember correctly, the dev site isn't set up for this?  

If this is good enough to say it's working, we can close this, or if there's a way I can receive the initial email notification for testing, please let me know.  Thanks!

**Comment by boonebgorges** [comment]
Hi Bree - Your email address is now set up as the instructor email for the WW-Dev section, so you should be able to test the last bit.

**Comment by bree-z** [comment]
A freebie!  I've already tested this and can confirm that faculty are directed to log into OL-WW after clicking on the link in the new question notification email.
