### ISSUE TITLE
Change styling of reply text

### ISSUE THREAD

**Issue by boonebgorges** [livinglab/webwork-for-wordpress#158]
> Reply text: Fix font size/line height. Currently too big/tight.
> .ww-question-content-text {
>   font-size: 1rem;
>   line-height: 1.5rem;

**Comment by jennaspevack** [comment]
Could this change also be applied to the reply text?  .ww-response-content, I think.

**Comment by boonebgorges** [comment]
Sure. I've made the change.

**Comment by bree-z** [comment]
This looks good, thanks!
