### ISSUE TITLE
Update ::selection styling

### ISSUE THREAD

**Issue by boonebgorges** [livinglab/webwork-for-wordpress#160]
> Selection elements are still teal, change bg to #b4c5e0.

**Comment by bree-z** [comment]
I think this looks good(?) I tested by highlighting some text, but is there anything I should look at?  If not, we can close this.  Thanks!

<img width="665" alt="Screen Shot 2019-06-16 at 6 38 34 PM" src="https://user-images.githubusercontent.com/7189824/59566891-c0629800-906e-11e9-9645-a6a3592b809d.png">

**Comment by boonebgorges** [comment]
This looks right to me - thanks, Bree!
