### ISSUE TITLE
"Question from..." styling

### ISSUE THREAD

**Issue by boonebgorges** [livinglab/webwork-for-wordpress#161]
See https://www.dropbox.com/s/k51njug4qvyt48s/OLWW_StyleGuide-miniupdate.png?dl=0 for hover etc.

**Comment by bree-z** [comment]
I think this looks good.  @jennaspevack , do you want to take a look just to double check? :)  Thanks!

**Comment by jennaspevack** [comment]
In the mockup I have the hover as black, no underline. 

Currently, on dev I'm seeing the hover as blue, no underline. Maybe we made this change I've forgotten? If not, I think the black, no underline still works.

**Comment by boonebgorges** [comment]
It was blue or black, depending on visited state. I must have misread the mockup, which indicates that it should be black regardless of visited state. (Note this means that there's no visual difference between visited-hover and unvisited-hover, though this seems like not a big deal to me.) I've made the change.

**Comment by bree-z** [comment]
Sorry, I misread the mockups too!  So, just to make sure I have this right, what I see is:

* Unvisited: blue w/underline
* Visited: black w/underline
* Hover (both visited and unvisited): black, no underline

If this is correct, I think we can close this. Thanks!

**Comment by boonebgorges** [comment]
This is getting shipped today. We can tweak for the next release if need be. Thank you!
