### ISSUE TITLE
Additional style adjustments

### ISSUE THREAD

**Issue by jennaspevack** [livinglab/webwork-for-wordpress#164]
@boonebgorges, I've been able to identify a few additional style adjustments. I _think_ they are small and won't affect other elements but should tighten things up and get us a little closer to the original mockups. Feel free to push to "future" if there are cascade issues I'm not aware of.

.item-stats.problem-stats {
    font-size: 1rem;
}

h3.ww-header {
    font-size: 1.4rem;
}

.ww-ask-question-form label {
    font-size: 1.4rem;
}

.ww-question-gloss {
    font-size: 1.1rem;
}

.anonymous-toggle label {
    line-height: 1.2rem;
    font-size: .85rem;
}

.index-intro > p {
    line-height: 2rem;
    font-size: 1.4rem;
}

.ww-author-name {
    font-size: 1.5rem;
}

**Comment by boonebgorges** [comment]
Sure thing. I've integrated the changes. Nothing jumps out at me as being in conflict, but if anything crops up, please let me know.

**Comment by bree-z** [comment]
Nothing has stuck out as being off while testing.  @jennaspevack, do you want to take a look at these?  Or point me to where I should look for them and I can double check?  

Thanks!

**Comment by jennaspevack** [comment]
I think this is all good. Thanks!
