### ISSUE TITLE
Answered/Unanswered question filter missing

### ISSUE THREAD

**Issue by bree-z** [livinglab/webwork-for-wordpress#166]
We're missing the fourth filter for answered/unanswered questions on openlabdev.org.  

I don't believe we wanted to get rid of it, but the choice for "Show In-Progress" should be removed.  

Thanks!
<img width="378" alt="FiltersDev" src="https://user-images.githubusercontent.com/7189824/59516065-31684b00-8ec9-11e9-8b47-c9779cacf8d8.png">
<img width="401" alt="FiltersProductionSite" src="https://user-images.githubusercontent.com/7189824/59516066-31684b00-8ec9-11e9-8a26-83e5316ee070.png">

**Comment by boonebgorges** [comment]
The original request was to remove the "This response answered my question" checkbox. Without that data, the filter does nothing. https://github.com/livinglab/webwork-for-wordpress/issues/154

Perhaps you want the logic of 'Show Answered' to do something different - essentially, what 'In-Progress' used to do, which is "show me questions that have at least some responses"?

**Comment by bree-z** [comment]
Whoops, sorry Boone!  I was filtering for "testing needed" and missed #154.  I was looking instead at the [style guide](https://www.dropbox.com/s/k51njug4qvyt48s/OLWW_StyleGuide-miniupdate.png?dl=0), which shows the filter with "Show In-Progress" removed, but I'm fine with removing it.   

Thanks!
