### ISSUE TITLE
Can't add alt text to images on mobile (round 2)

### ISSUE THREAD

**Issue by bree-z** [livinglab/webwork-for-wordpress#167]
Hi Boone, 

I appear to be having the same issue as reported in #122 adding alt text on mobile (sorry!).  I tested using Chrome on an iPhone 7/iOS 12.2 and Android 8.0/Chrome.

Thanks!

**Comment by boonebgorges** [comment]
The problem appears to be specific to when you open the media modal and it's in 'Upload Files' view. If you start from 'My Uploaded Files', the attachment "drawer" appears to work fine. 

I've just pushed a change that is intended to make the behavior more consistent between the views.

**Comment by bree-z** [comment]
Thanks, Boone!  I'm now able to add alt text.
