### ISSUE TITLE
Respond to this question box resize

### ISSUE THREAD

**Issue by jennaspevack** [livinglab/webwork-for-wordpress#168]
@boonebgorges while testing I noticed that the Respond to this Question textarea box resizes in an unexpected way. Don't think it affects functionality, but I guess I expected to only be able to drag the box down to expand rather than in all directions. Just thought I'd point it out in case it was unintended.

https://www.dropbox.com/s/vs0chqqbdasbchc/respondboxresizes.mov?dl=0

**Comment by boonebgorges** [comment]
In general, textareas are resizable along both x and y axes, unless you specify that they aren't. We didn't specify that they aren't. I've made the change, and I've enforced a minimum height - this way, you can make it taller than the default, but not smaller (and can't adjust the width at all0.

**Comment by bree-z** [comment]
Thanks, Boone.  This looks good. I'm able to make the box taller, but not shorter or wider.
