### ISSUE TITLE
Permissions issue when testing image uploads on test site

### ISSUE THREAD

**Issue by bree-z** [livinglab/webwork-for-wordpress#183]
Hi Boone, 

I was logged in as bree_student2 on hardg.com/webwork, and tried to upload an image with my question. I got the following error message: 

Unable to create directory wp-content/uploads/2020/05. Is its parent directory writable by the server?

URL: https://hardg.com/webwork/?post_data_key=webwork_post_data_8a3824a6655a6d065939d981999b9fd5#:problemId=CUNY/CityTech/Precalculus/setPolynomial_Division/intro-long-division.pg

Thanks!

<img width="566" alt="Screen Shot 2020-05-11 at 2 29 14 PM" src="https://user-images.githubusercontent.com/7189824/81599024-32825080-9396-11ea-92f7-bf6b33f4eaed.png">

**Comment by boonebgorges** [comment]
Thanks for the report. Could you try again please?

**Comment by bree-z** [comment]
Thanks Boone! I'm able to upload images now.
