### ISSUE TITLE
In question list, all questions are marked 'unanswered' 

### ISSUE THREAD

**Issue by moui72** [livinglab/webwork-for-wordpress#23]
Looking at the [openlabdev webwork site](http://openlabdev.org/webwork-playground/#results): No matter what filter I apply, even showing "only answered questions," all questions are marked as unanswered in the list of questions that are displayed.

The filter does change the set of display questions: "answered" gives me only questions where I have clicked I personally have clicked the "this answered my question" box on a response, and the "unanswered" filter excludes those.

When I click on a question, it will be marked unanswered unless I personally have clicked the "this answered my question" box on a response.

Windows, FF 46

**Comment by boonebgorges** [comment]
Thanks for the detailed report, @moui72. The logic that determined the "answered" highlighting was originally built for the single-problem view, and when the index view was introduced and rewritten, the logic wasn't carried over. I've addressed these issues in the commits referenced above. 

Appears to be working as expected on http://openlabdev.org/webwork-playground/.

**Comment by moui72** [comment]
looks right now

**Comment by boonebgorges** [comment]
Thanks, @moui72 !
