### ISSUE TITLE
When viewing a problem, the filters don't work

### ISSUE THREAD

**Issue by moui72** [livinglab/webwork-for-wordpress#25]
When I am viewing a problem, the "answered" and "unanswered" filters return the same set of questions.

**Comment by boonebgorges** [comment]
This was due to an unrelated JS error, which was short-circuiting the resetting of the application state. It's working properly now on openlabdev.org

**Comment by moui72** [comment]
Great! I'll check again in a bit.

**Comment by moui72** [comment]
looks fixed!

**Comment by boonebgorges** [comment]
Thanks for verifying!
