### ISSUE TITLE
"Respond" button takes me to main WW site / list of all questions

### ISSUE THREAD

**Issue by jonasreitz** [livinglab/webwork-for-wordpress#26]
The Respond button:  instead of taking me to the response box for the particular question (where I clicked it), it takes me to what seems to be the main list of  questions, sorted by "Recent Activity".  Here are  details:

In webwork I clicked "Ask for Help" here: 
http://mathww.citytech.cuny.edu/webwork2/WW-Dev/1-RationalExpressions/2/?user=jreitz&effectiveUser=jreitz&key=ljrTUsYrD5tNVd2LFQfuCqrZSAYrzRXJ&displayMode=MathJax&showOldAnswers=1 

On the resulting page, I asked a question: 
http://openlabdev.org/webwork-playground/#/problem/Library/FortLewis/Algebra/2-4-Algebraic-fractions/MCH1-2-4-04-Algebraic-fractions.pg 
(Boone - based on your previous comments, I'm not sure if this URL will work, although I did ask a question which may have forced the page to be created.  Let me know if you want me to duplicate the problem & take screenshots).

And, after asking the question, I clicked "Respond", which took me to the main WW Playground site, sorted by Recent Activity:
http://openlabdev.org/webwork-playground/# 

Since the question I was responding to happened to be at the top of the Activity list, I was able to respond to it there without problem - but that's a lucky coincidence, I'm guessing.

This problem seems to happen regardless of whether it is a "new question" (one I just asked) or an existing question on the site - I tried again a few different ways with the same result. 

I'm on Chrome Version 52.0.2743.116 (64-bit), OS X El Capitan.

**Comment by boonebgorges** [comment]
Thanks for the detailed description, @jonasreitz !

I believe I found the root cause of the problem. Could you test the behavior again on http://openlabdev.org/webwork-playground/?

**Comment by jonasreitz** [comment]
Seems to work fine now - thanks, Boone!

**Comment by boonebgorges** [comment]
Thanks for testing!
