### ISSUE TITLE
Problem information sometimes doesn't persist through OpenLab login

### ISSUE THREAD

**Issue by jonasreitz** [livinglab/webwork-for-wordpress#3]
That is, after clicking the "Ask for Help" button in WW and logging in to the OpenLab, I'm presented with "You are asking a question about Problem Set #0" and the "Show problem" button reveals an empty box when clicked .  The "Dump of data WeBWorK sends over" box reads:

```Array
(
    [remote_class_url] => http://mathww.citytech.cuny.edu/webwork2/WW-Dev/
    [remote_referer_url] => http://mathww.citytech.cuny.edu/webwork2/WW-Dev/
)
```

I believe the necessary conditions for this behavior are:
1.  Having entered a (wrong) answer into WeBWorK and clicked "Check Answer" there, prior to asking for help, and 
2.  Not being logged in to OpenLab.

If either of these conditions are not met, it seems to retain the problem information just fine.

**Comment by boonebgorges** [comment]
Thanks for the detailed report! There must be something special about 
the way WeBWorK packages data for "Ask for Help" after a failed answer 
submission. I'll look into it.

**Comment by drdrew42** [comment]
I am going to speculate that this may only be an issue with the initial HTML authentication, prior to signing into OpenLab-Dev. I've saved the HTML authentication username and password into my browser, and have not run into this issue when OpenLab forces authentication.

**Comment by boonebgorges** [comment]
This has been rewritten, so I'm going to mark the issue as resolved. If it comes up again, we can readdress.
