### ISSUE TITLE
Problems containing html and css are rendered as text

### ISSUE THREAD

**Issue by moui72** [livinglab/webwork-for-wordpress#32]
[Problems containing html and css](http://openlabdev.org/webwork-playground/?post_data_key=webwork_post_data_8b7b9cdad28720e1a57cb607f96bcfeb#/problem/local/ParabolaVertices/vertex-CtS-walkthrough.pg) are rendered as text rather than the html and css being interpreted by the browser. Angled brackets are transformed to html entities (`&lt;`, `&gt;`).

![misrendered htmlcss](https://cloud.githubusercontent.com/assets/3885628/18449155/239760be-78fc-11e6-8593-4621845fe46e.png)

latex seems to render correctly.

webwork url: http://mathww.citytech.cuny.edu/webwork2/WW-Dev/ParabolaVertices-CtS/1/?user=tpeckenpaugh&effectiveUser=tpeckenpaugh&key=yTNvez9EZ3wp5TWXvb1Gd1t6H7gmNOZb

openlabdev url: http://openlabdev.org/webwork-playground/?post_data_key=webwork_post_data_8b7b9cdad28720e1a57cb607f96bcfeb#/problem/local/ParabolaVertices/vertex-CtS-walkthrough.pg

Win7/Chrome 52+

**Comment by boonebgorges** [comment]
Thanks for the report. We need to come up with a whitelist of markup 
that is going to be interpreted, with the rest being stripped. For 
security and aesthetic reasons, we can't allow it all through blindly.

**Comment by drdrew42** [comment]
Just to clarify, which set and problem number is this coming from?

**Comment by boonebgorges** [comment]
URLs from both WW and from WP would be helful in this case (and most cases!)

**Comment by moui72** [comment]
Understood. I'll provide URLs when I get home in an hour or so.

**Comment by moui72** [comment]
I added URLs to the original post and repeat them below

webwork url: http://mathww.citytech.cuny.edu/webwork2/WW-Dev/ParabolaVertices-CtS/1/?user=tpeckenpaugh&effectiveUser=tpeckenpaugh&key=yTNvez9EZ3wp5TWXvb1Gd1t6H7gmNOZb

openlabdev url: http://openlabdev.org/webwork-playground/?post_data_key=webwork_post_data_8b7b9cdad28720e1a57cb607f96bcfeb#/problem/local/ParabolaVertices/vertex-CtS-walkthrough.pg

**Comment by bree-z** [comment]
Would it be useful to add URLs here if we encounter any additional instances of this problem, other than what Tyler reports above?  

Thanks!

**Comment by boonebgorges** [comment]
Hi Bree - Sure, feel free to list additional links if they demonstrate 
different kinds of parse failures (ie, different tags)

**Comment by bree-z** [comment]
Ok, will do if I see any.  Thanks!

**Comment by bree-z** [comment]
Hi Boone - Not sure 8if this is helpful, but here's a problem with ol and ul tags:

openlabdev URL: http://openlabdev.org/webwork-playground/#/problem/local/CompoundInterest/different-rates.pg/question-11108

WW URL: http://mathww.citytech.cuny.edu/webwork2/WW-Dev/CompoundInterest/1/?user=bzuckerman&key=OWiBHhKJsOALZni3oiA9rIJBanglOd2k&effectiveUser=bzuckerman

**Comment by moui72** [comment]
Here's my best effort to categorize the problems with special rendering needs

type  | description | ol url | ww url
:-----|:------------|:-------|:------
image | problem contains an image | [GraphingSineCosine](http://openlabdev.org/webwork-playground/#/problem/local/GraphingSineCosine/identify-amplitude.pg/question-11071) | [GraphingSineCosine](http://mathww.citytech.cuny.edu/webwork2/WW-Dev/GraphingSineCosine/1/?user=tpeckenpaugh&key=l9FPbyWS7yDmavaJeAVR06F1naQsbK7T&effectiveUser=tpeckenpaugh)
scaffold | problem is scaffolded | [ParabolaVertices-CtS](http://openlabdev.org/webwork-playground/#/problem/local/ParabolaVertices/vertex-CtS-walkthrough-fractions.pg/question-11080) | [ParabolaVertices-CtS/](http://mathww.citytech.cuny.edu/webwork2/WW-Dev/ParabolaVertices-CtS/1/?user=tpeckenpaugh&effectiveUser=tpeckenpaugh&key=l9FPbyWS7yDmavaJeAVR06F1naQsbK7T)
multipart | problem requires more than one answer | [CompoundInterest](http://openlabdev.org/webwork-playground/?post_data_key=webwork_post_data_bd62d366433bb813d454153543524c33#/problem/local/CompoundInterest/different-rates.pg) | [CompoundInterest](http://mathww.citytech.cuny.edu/webwork2/WW-Dev/CompoundInterest/2/)

**Comment by boonebgorges** [comment]
I've got most of this working. Here are some examples:

- scaffolding is functional (I think?) though needs design work: http://openlabdev.org/webwork-playground/#/problem/local/ParabolaVertices/vertex-CtS-walkthrough-fractions.pg/question-11080
- Most generic markup is now handled, though it's based on a whitelist, so it's likely that we'll come across tags that I have missed. See eg http://openlabdev.org/webwork-playground/?post_data_key=webwork_post_data_bd62d366433bb813d454153543524c33#/problem/local/CompoundInterest/different-rates.pg
- I'm translating image tags at the time of import, so you'll see that images work properly for new problems. For example, if you try asking a question about http://mathww.citytech.cuny.edu/webwork2/WW-Dev/GraphingSineCosine/2/?key=ngMsds6YvLCch33CdqaLGBxxI8NVicsi&user=bgorges&effectiveUser=tpeckenpaugh This is not a great long-term solution - I think we should probably copy the image over to WP at the time of question creation - but it'll work for the time being.

**Comment by drdrew42** [comment]
These are all working for me - with one small exception.

For the third bullet: when this question is pulled over to the OL site, it seems as though the "sin(x)" and "cos(x)" are being stripped from the first question below the graph.

What should appear is "Does this graph have the shape of \sin(x) or \cos(x) ? ___" 
But what's appearing instead is "Does this graph have the shape of  or  ? ___"

**Comment by boonebgorges** [comment]
Thanks @drdrew42 - I will look into it.

**Comment by moui72** [comment]
Looking good for the ones I've gotten to.

One comment about the scaffold ones (e.g. http://openlabdev.org/webwork-playground/#/problem/local/ParabolaVertices/vertex-CtS-walkthrough-fractions.pg/question-11080), I wonder if we should/could change the yellow background of the section headers to be either blue or black (with white text) so it fits in a bit better. 

I include the css suggestion below mostly just to blame the class definition that is giving us the yellow color.

e.g.

```css
.canopen {
    background: yellow!important;
}
```
might become

```css
.canopen {
  background-color: #0044af;
  color: #fff;
  font-weight: 600;
}
```

**Comment by boonebgorges** [comment]
@moui72 - Yeah, I agree that somithng should be done about the colors :) Let's talk this over briefly during tomorrow's meeting.

**Comment by moui72** [comment]
In general, Boone, would you rather we report markup issues here or make new issues? E.g. #50  should maybe have been part of this thread?

**Comment by boonebgorges** [comment]
Start new issues. These massive threads lead to reports getting lost. In fact, let's close this one.
