### ISSUE TITLE
about and help page should be accessible

### ISSUE THREAD

**Issue by moui72** [livinglab/webwork-for-wordpress#33]
not sure if this is using SPA-style view population or if the about and help pages should have their own URLs and simply aren't created yet, but currently all the menu links resolve to the homepage

I am sure we're aware of this, but I am making an issue so I'll know when content is added and I can take a look :)

**Comment by boonebgorges** [comment]
Yup, no content has been created for these pages yet. Thanks for 
creating the ticket :-D
