### ISSUE TITLE
after asking a question, reply field is in preview mode

### ISSUE THREAD

**Issue by moui72** [livinglab/webwork-for-wordpress#34]
after I asked a question about a problem, if I go to reply to myself (admittedly this may be an edge use case) the reply field is grayed out because I am in preview mode. I have to click 'edit' to enter text. This is a bit unintuitive. 

![response preview](https://cloud.githubusercontent.com/assets/3885628/18450242/35af5442-7900-11e6-9ad2-efd370ef2c45.png)

WeBWorK url: http://mathww.citytech.cuny.edu/webwork2/WW-Dev/AddRationalExpressions2/50331648/?user=tpeckenpaugh&key=yTNvez9EZ3wp5TWXvb1Gd1t6H7gmNOZb&effectiveUser=tpeckenpaugh

OpenLab Dev url: http://openlabdev.org/webwork-playground/#/problem/local/AddRationalExpressions/diff-binomial-med.pg/question-11073

**Comment by boonebgorges** [comment]
Good catch! Should be fixed by 52264f9. Ready for testing.

**Comment by moui72** [comment]
Yes, looks good!

I noticed a related issue, though: if I submit a reply from preview mode, the field gets cleared but stays in preview mode, so I then have to click edit to reply again. I think it should go back to edit mode. Admittedly this is not likely to matter most of the time, but I just think it looks better :eyeglasses: 

let me know if you would prefer a new issue for this

![submitreplyinpreview](https://cloud.githubusercontent.com/assets/3885628/18522470/32ee17c8-7a7e-11e6-906b-ced7aa80de05.png)

**Comment by boonebgorges** [comment]
>  I think it should go back to edit mode.

Good catch! I hadn't thought of that. I've made the change.

**Comment by moui72** [comment]
this issue has come back. when I asked a question from http://openlabdev.org/webwork-playground/#:problemId=local/CoordinatePlaneTrig/ratio-inequality-xyr.pg:questionId=11392 it posted and scrolled as expected, but the reply field was in 'preview' mode such that I needed to click 'edit' in order to enter text

![q-r-edit](https://user-images.githubusercontent.com/3885628/28691003-575eebbe-72e9-11e7-821e-4f4b0fa0d04f.png)

**Comment by boonebgorges** [comment]
Thanks for pointing this out, @moui72. This was caused by some refactoring related to editable fields. It should now be resolved.

**Comment by moui72** [comment]
yep!
