### ISSUE TITLE
Wrong "most votes" sort for question list

### ISSUE THREAD

**Issue by moui72** [livinglab/webwork-for-wordpress#35]
Most votes sort is the same as most replies sort

To recreate: http://openlabdev.org/webwork-playground
* From homepage, filter by course -> WW
* Sort dropdown -> most votes

![sortorder](https://cloud.githubusercontent.com/assets/3885628/18457334/de591acc-7925-11e6-957c-2f54debdd395.png)

**Comment by boonebgorges** [comment]
I think this is sorted now (no pun intended). Ready to test on openlabdev.org/webwork-playground

**Comment by moui72** [comment]
yep, looks right to me now :+1:
