### ISSUE TITLE
"ask a question" form should not suggest reviewing non-existent questions

### ISSUE THREAD

**Issue by moui72** [livinglab/webwork-for-wordpress#36]
When asking a question about a problem that has no existing questions, the form still suggests that you should review other questions first. That text should be hidden in that case.

URL (provided no one has asked a question about this problem since I made this post)
http://openlabdev.org/webwork-playground/?post_data_key=webwork_post_data_8abb64930358afa5cb9b0e67dfc42ff1#/problem/local/ComplexFractions-Method2/separated-reduce-DoS-med.pg

![reviewnoquestions](https://cloud.githubusercontent.com/assets/3885628/18457501/620c421c-7927-11e6-9268-83ed3eed3bfd.png)

**Comment by boonebgorges** [comment]
Good call. Fix is ready to test.

**Comment by moui72** [comment]
yes, looks good!
