### ISSUE TITLE
Ensure that scaffolded problems are maximally "open" on import

### ISSUE THREAD

**Issue by boonebgorges** [livinglab/webwork-for-wordpress#40]
Markup that comes from an admin WW account will have all of the problems labeled as "open". Make sure this is the case with student accounts, too. If it's not, make it so (I assume it's handled by specific CSS classes or something like that).

cc @moui72, who I think added this to his testing script :)

**Comment by bree-z** [comment]
It looks like these problems are not fully open for student accounts.  I'm only able to see the first step of a problem on OLdev.  If I answer the first step correctly in WW and move on to step 2, after I Ask a Question, I still only see the first part on OL.  

The screenshot below is after I'd answered step 1 correctly in WW, and moved on to step 2.

![scaffolded_step1only](https://cloud.githubusercontent.com/assets/7189824/18924525/82a15540-857e-11e6-936f-5428dcfb227b.png)

WW URL: http://mathww.citytech.cuny.edu/webwork2/WW-Dev/ParabolaVertices-CtS/4/
OL URL: http://openlabdev.org/webwork-playground/#/problem/local/ParabolaVertices/vertex-CtS-walkthrough-fractions-hard.pg

(I stole this one from @moui72) :)

**Comment by boonebgorges** [comment]
@bree-z Thanks for verifying this.

I've just reproduced. The incomplete steps are represented by empty `<div>` elements in the markup sent over by WW. That means that the full problem data is not available to OL. There's nothing we can do to work around this for the moment.

One mitigating factor - and maybe a feature rather than a bug! - is that the problem text will be frozen in time, representing the state of the student who asked the question, at the time that the question was asked. This will be different for each question, so that users who are further along will have more sections available.

I'm going to flag this ticket as one that should be revisited when/if we decide to integrate more closely with WW's actual API.

**Comment by moui72** [comment]
as a quick note, your description is correct, but the first person to ask a question will lock their version of the problem in as the "main" problem (displayed at the top). Subsequent askers will have different versions embedded in their questions, but the "main" one will always be the first. Unless this changes depending on the OL account you're logged in with?

I've also just noticed that the LaTeX in the section headings is not rendered correctly: 

    Step 2: Divide off the coefficient of [`x^2`] 

ol url: http://openlabdev.org/webwork-playground/#/problem/local/ParabolaVertices/vertex-CtS-walkthrough-fractions-medium.pg/question-11148

ww url: http://mathww.citytech.cuny.edu/webwork2/WW-Dev/ParabolaVertices-CtS/3/?user=student1&effectiveUser=student1&key=jvXdviizA6F8FWauC2RH8jVwTKzSYICN

![image](https://cloud.githubusercontent.com/assets/3885628/18929237/b0033cfc-8591-11e6-86e9-15a9402ec6a9.png)

**Comment by bree-z** [comment]
Hi @boonebgorges and @moui72 - just a note about the LaTeX in the section headings not being rendered correctly -- this is something I did, but didn't have a chance to put in a ticket earlier.  What happened is this:

When I clicked on Step 2 (“Divide off the coefficient of x^2”) to expand it, I happened to click exactly on the LaTeX part of the question.  First, it disappeared altogether, and then after submitting my question, the x^2 reappeared as plain text.  

Here's a "disappeared" screenshot (before submitting the question):

![disappearinglatex](https://cloud.githubusercontent.com/assets/7189824/18933364/69f58b1e-85a2-11e6-9045-0118e6000423.png)

**Comment by boonebgorges** [comment]
> as a quick note, your description is correct, but the first person to ask a question will lock their version of the problem in as the "main" problem (displayed at the top). Subsequent askers will have different versions embedded in their questions, but the "main" one will always be the first. Unless this changes depending on the OL account you're logged in with?

@moui72 See https://github.com/livinglab/webwork-for-wordpress/issues/44#issuecomment-250183219 for some explanation of how this works. 

I'm going to break off discussion of the LaTeX stuff into another thread.

**Comment by drdrew42** [comment]
I've also fixed this issue - these were the wrong delimiters for this situation. The Step-headers are _outside_ of the PGML, and as such I was using the wrong delimiters - this one's on me. :(

**Comment by boonebgorges** [comment]
See also #13.

**Comment by moui72** [comment]
I think this is done but I am not sure

**Comment by drdrew42** [comment]
Yes, I believe this one was on my end, and has been rectified.
