### ISSUE TITLE
"reply" link is visible when not logged in to openlab

### ISSUE THREAD

**Issue by moui72** [livinglab/webwork-for-wordpress#42]
When I look at the openlab-ww site but I'm not logged in to the OL, there is a "reply" link listed under each reply, which simply resolves to a blank hash (i.e. http://openlabdev.org/webwork-playground/[?QUERY]#). The reply form is (correctly) not visible

I don't think this reply link should be visible.

![notloggedin reply](https://cloud.githubusercontent.com/assets/3885628/18754259/0e0e5812-80b6-11e6-8bb7-4b2f8ecdf01c.png)

**Comment by boonebgorges** [comment]
Good call - thanks for the report and the screenshot.

**Comment by boonebgorges** [comment]
Ready for testing.

**Comment by moui72** [comment]
it's gone! :dash:
