### ISSUE TITLE
when marking a question as answered, question header does not change until reload

### ISSUE THREAD

**Issue by moui72** [livinglab/webwork-for-wordpress#45]
![olww-markanswer-qheader](https://cloud.githubusercontent.com/assets/3885628/18925398/daaaba9e-8581-11e6-9e59-0ae454105dd7.png)

Super minor issue.

Related to #29 -- when a reply is marked as an answer it is immediately marked as such. but the question's header does not change from "answered" to "unanswered" until next page load.

e.g. http://openlabdev.org/webwork-playground/#/problem/local/AddRationalExpressions/diff-mono-easy.pg

**Comment by boonebgorges** [comment]
Good catch! Should be fixed now on openlabdev.org.

**Comment by moui72** [comment]
looks good now =]
