### ISSUE TITLE
"this answered my question" permissions

### ISSUE THREAD

**Issue by moui72** [livinglab/webwork-for-wordpress#46]
If I am logged in as teststudent and I am viewing a question posted by someone else, I can check and uncheck the "this answered my question" box. this will toggle the blue bar on the left, but have no persistent effect. 

I think the check boxes should be disabled if I don't have permission to manipulate them

e.g. http://openlabdev.org/webwork-playground/#/problem/local/GraphingSineCosine/identify-period.pg/question-11110

![answered-permissions](https://cloud.githubusercontent.com/assets/3885628/18925494/2d380d20-8582-11e6-856a-7b26a4b03c48.png)

**Comment by boonebgorges** [comment]
Good catch. This was due to a typo in the filter that maps OpenLab filter types onto certain WWOL permissions. Fix is ready to test.

**Comment by bree-z** [comment]
This is fixed.  I no longer see the checkbox to mark as answered when viewing another user's question, if logged in as a student.  I can see and check it when logged in as testfaculty.

**Comment by boonebgorges** [comment]
Thanks!
