### ISSUE TITLE
ability to "clear" filters

### ISSUE THREAD

**Issue by moui72** [livinglab/webwork-for-wordpress#47]
There is no way to reset a filter to "off" state -- you can only change its value.

For example: if I filter to a particular problem set and then I want to go back and look at all unanswered questions, I have to navigate to "home" to clear the problem set filter.

It might be nice to have a "show all" for the higher level filters (problem set, section, course) like there is for answered/unanswered.

![clear-filter](https://cloud.githubusercontent.com/assets/3885628/18925639/c24b09d0-8582-11e6-96eb-c683437c3234.png)

**Comment by boonebgorges** [comment]
Good call. I've added Show All to each filter. It's slightly awkward, because selecting Show All will result in the "Select Course" etc filter value being shown (instead of "Show All"). Play with it and see if it makes sense to you. If it feels weird, we can ask Jenna for help.

**Comment by moui72** [comment]
I think it's good now, no complaints. Maybe @bree-z could also take a quick look and see what she thinks?

**Comment by bree-z** [comment]
I agree that it's slightly awkward - I think it would be better to have some visual reminder that users have filtered for "All".  But this is better than no "Show All" option, so maybe this is something to improve in the next iteration?

**Comment by boonebgorges** [comment]
Yeah. The problem with that is that "Show All" is actually the same thing as "Select Course" or whatever, so it feels weird and redundant to have Show All be a persistent value. 

I think what we currently have is good enough for now. I doubt anyone will find this awkward in actual use, but if they do, we can bring it to Jenna's attention for further study.
