### ISSUE TITLE
"Main" problem differs slightly from embedded version

### ISSUE THREAD

**Issue by moui72** [livinglab/webwork-for-wordpress#50]
This is a minor issue.

Questions that have a drop-down field for the response entry are rendered differently at the top of a question detail page vs. when embedded within a question.

Main problem renders the dropdown.
![dropdown-mainprob](https://cloud.githubusercontent.com/assets/3885628/18926572/5590db68-8586-11e6-83b1-6424463f7cd4.png)

Embedded problem renders just the options in sequence as text.
![dropdown-embeddedprob](https://cloud.githubusercontent.com/assets/3885628/18926576/6346bd4a-8586-11e6-95ab-6a976ae2300d.png)

The spacing in embedded problems is also somewhat compressed.

ww: http://mathww.citytech.cuny.edu/webwork2/WW-Dev/GraphingSineCosine/4/?key=5rw1HOb7lGIWjUhj1zZT1dwWhlINvYL2&user=student2&effectiveUser=student2
ol: http://openlabdev.org/webwork-playground/#/problem/local/GraphingSineCosine/function-graphing.pg

**Comment by boonebgorges** [comment]
Ah, I didn't have `select` and `option` on the markup whitelist for problem text. They've been added. Ready to test - make sure you test with a *new* question, as anything already saved in the database will already have had these tags stripped.

**Comment by moui72** [comment]
I can't find any other questions with a dropdown.

@drdrew42 confirm/deny?

**Comment by drdrew42** [comment]
This may be the only one in the sets I've loaded into WW-Dev. Let me double-check.

**Comment by drdrew42** [comment]
I've added a fifth problem to the GraphingSineCosine set - it also uses dropdown and has a different pathID.

**Comment by moui72** [comment]
Thanks!

**Comment by moui72** [comment]
the dropdown is now rendered as a dropdown in embedded problems.

I noticed something else in checking this but I will make a new issue

![dd-ok](https://cloud.githubusercontent.com/assets/3885628/18973508/cd5a26b4-866b-11e6-92ac-d3537bdcb0b4.png)
