### ISSUE TITLE
filters not visible on android 7 / chrome 53+

### ISSUE THREAD

**Issue by moui72** [livinglab/webwork-for-wordpress#51]
The whole "explore questions box" is simply omitted (it does not appear above or below the list of questions)

Nexus 5X, Android 7, Chrome 53+ (also FF 49)

ol-url: http://openlabdev.org/webwork-playground/

![image](https://cloud.githubusercontent.com/assets/3885628/18930015/625caec2-8594-11e6-88d1-c1d1a937af85.png)

**Comment by boonebgorges** [comment]
I believe it should appear when clicking the magnifying glass.

**Comment by moui72** [comment]
so it does! ;D

**Comment by moui72** [comment]
I'm not sure if you did anything, but the search form no longer appears above the filters, and when it appears below the page content it looks fine -- so I am closing this :grinning:

**Comment by boonebgorges** [comment]
I love bugs that fix themselves
