### ISSUE TITLE
LaTeX delimiters [` and `] ?

### ISSUE THREAD

**Issue by boonebgorges** [livinglab/webwork-for-wordpress#52]
See https://github.com/livinglab/webwork-for-wordpress/issues/40#issuecomment-250277642 and subsequent discussion.

It appears that some content in WeBWorK uses [{backtick}... {backtick}] as LaTeX delimiters (backtick is a special character on GitHub and I can't figure out how to escape it). WeBWorK appears to handle this rendering natively, sending the delimiters intact in the POST data it sends to WP. This is in contrast with other LaTeX strings, which are preprocessed into Mathjax `<script>` tags.

@drdrew42 Do you have some insight into what's happening here? Did you enter these delimiters, or are they an interpolation of WeBWorK's, perhaps to account for the fact that it appears in the context of an HTML tag?

**Comment by drdrew42** [comment]
This is a difference between PG problems and PGML problems. In PG the delimiters are \( \) and in PGML they're [` `]. So this may be a big problem, as the plan was to shift the problem sets that were written early on (in PG) over to PGML for standardization purposes.

**Comment by boonebgorges** [comment]
@drdrew42 When you say "this may be a big problem", do you mean "it needs to be fixed right now"? Are there problems in the current sets that are exhibiting the issue? If so, could you link to them please?

**Comment by drdrew42** [comment]
I'm not seeing it cause problems now, and we've already crossed into the newest sets that are strictly PGML. Did you already make exceptions for these delimiters? (I see that this comment was posted a month ago...)

**Comment by boonebgorges** [comment]
I don't recall :) If you can link to a problem whose source contains 
this kind of delimiter, I can trace it through the database to get a 
sense of what's happening.

**Comment by drdrew42** [comment]
All of the questions on the current ol-webwork site are coming from PGML coded problems.

**Comment by boonebgorges** [comment]
Yes, but in the original discussion, I think it was specified that only certain bits of TeX (like in multi-part problems) were delimited like this. I want to be sure that I'm looking at the right thing before digging deep. Can you confirm that https://openlab.citytech.cuny.edu/ol-webwork/#/problem/local/Circles/identify-center-radical-radius-CtS.pg/question-145 contains markup that was originally delimited in this way?

**Comment by drdrew42** [comment]
$(U

>>> Boone Gorges <notifications@github.com> 10/31/2016 9:57 AM >>>

Yes, but in the original discussion, I think it was specified that only certain bits of TeX (like in multi-part problems) were delimited like this. I want to be sure that I'm looking at the right thing before digging deep. Can you confirm that https://openlab.citytech.cuny.edu/ol-webwork/#/problem/local/Circles/identify-center-radical-radius-CtS.pg/question-145 contains markup that was originally delimited in this way?

**Comment by drdrew42** [comment]
Yes, it certainly is. Would it help if I provided a WW login for the class I'm using with ol-webwork right now?

**Comment by boonebgorges** [comment]
Yes, if it's not too much trouble. Thanks.

**Comment by drdrew42** [comment]
And I think you might be referring to the "displaystyle" math from PG, which uses the delimiters \[ \]

PGML: [{tick} {tick}] and PG: \( \) as \begin{math} \end{math}
PGML: [{tick}{tick} {tick}{tick}] and PG: \[ \] as displaystyle

**Comment by drdrew42** [comment]
http://mathww.citytech.cuny.edu/webwork2/MAT1275-F16-Parker
with the usual 'bgorges'

**Comment by boonebgorges** [comment]
what I was originally referring to was what this screenshot shows: https://github.com/livinglab/webwork-for-wordpress/issues/40#issuecomment-250277642

The LaTeX in "Step 2" is not rendered properly in this example, because WeBWorK doesn't render it before sending it to WP.

**Comment by boonebgorges** [comment]
Hiya @drdrew42 - If I'm correct that https://github.com/livinglab/webwork-for-wordpress/issues/40#issuecomment-257371294 refers specifically to the issue described in this ticket, then I think we can close this one as a non-issue :-D

**Comment by drdrew42** [comment]
Yeah, that's also my bad, resurrecting a month-old issue. I just saw it mentioned me and I somehow missed responding to it.

**Comment by boonebgorges** [comment]
No worries! Always happy to close a ticket :)
