### ISSUE TITLE
Cannot Ask a Question on Mobile

### ISSUE THREAD

**Issue by bree-z** [livinglab/webwork-for-wordpress#53]
I'm on iOS 10/Safari.  

After clicking Ask a Question from WW, the post_data_key param does not appear to be passed.  I just end up at http://openlabdev.org/webwork-playground/ with nowhere to ask my question. 

WW URL: http://mathww.citytech.cuny.edu/webwork2/WW-Dev/CompoundInterest/1/?key=esvrg7KNPgvyEbWH4MWwA3e9Bu4UeZeN&user=student1&effectiveUser=student1

cc @moui72

**Comment by bree-z** [comment]
And not sure if the screenshot is helpful here, but here it is:

![mobileaskaquestion](https://cloud.githubusercontent.com/assets/7189824/18967050/bcf1ba36-8651-11e6-894a-df32459bba6f.PNG)

**Comment by bree-z** [comment]
Sorry!  Just realized I pasted the wrong URL.  I tested this twice - once with the student11 account and a second time with bzuckerman.  Here's the URL from the second mobile test:

http://mathww.citytech.cuny.edu/webwork2/WW-Dev/CompoundInterest/1/?effectiveUser=student1&user=bzuckerman&key=a1MIK1czBY6diDBlKALe2mPYZL4rtdI7

But it appears I was bzuckerman "acting as" student1.  I'll test again from scratch just to be sure...

**Comment by bree-z** [comment]
No, I get the same result.  I tried again as student1 on this problem:

http://mathww.citytech.cuny.edu/webwork2/WW-Dev/CompoundInterest/1/?key=0UHRERBK33suHrGIRbFavQs3S9VmITL3&user=student1&effectiveUser=student1

One more thing though, I did get a warning about OLdev as a possible phishing site.  I ignored the warning, but just fyi in case that's part of the problem.

**Comment by boonebgorges** [comment]
I've reproduced, but only on iOS Safari, not any Android browser. I'm 
guessing it's due to the phishing notice. I'll look into it.

**Comment by boonebgorges** [comment]
I believe I've confirmed that it's the "phishing" notice. @bree-z, please try the following:

- Go to your iOS Settings > Safari
- Under Privacy and Security, uncheck Fraudulent Website Warning

Then try the WW-OL handshake again. It should work.

What must be happening is that Safari is discarding the contents of the POST request when it inserts the warning.

If it's working for you with the Settings change, we can probably close this ticket. It won't be an issue on the production site, where we don't have to send HTTP auth credentials as part of the URL. (Also, you can change your settings back if you'd like :) )

**Comment by bree-z** [comment]
Ok, looks good, thanks!

Closing this one.  :)
