### ISSUE TITLE
After filtering for a problem set, question title links must be clicked twice to view question detail

### ISSUE THREAD

**Issue by bree-z** [livinglab/webwork-for-wordpress#54]
Here's what I did: 

- I filter for a problem set (e.g. AddRationalExpressions2)
- When I try to click on the title of a question ("Question from Test Student") to view the question detail, nothing happens.  
- If I click again, then I can view the question detail.  Or, if I click something else first, like "View my Problem" the link works as expected.

I'm using OSX/FF 49.0.1 and Chrome 53.

**Comment by boonebgorges** [comment]
Thanks for the details. This was due to a bug in the way the mobile menu toggle worked (the magnifying glass). It should be fixed now. Please test both the functionality you've described here (the double clicks) and also do a sanity check on the magnifying glass filters while on mobile.

**Comment by moui72** [comment]
seems to be working on Android 7 / Chrome 53

**Comment by bree-z** [comment]
Looks good to me, too, thanks!  I tested both the links and filters on mobile, and both are fine.  I did just see one more unrelated issue on mobile, for which I'll open a separate ticket.
