### ISSUE TITLE
clicking elements (e.g. img or select) within embedded problem collapses the problem

### ISSUE THREAD

**Issue by moui72** [livinglab/webwork-for-wordpress#55]
When you click the dropdown in an embedded question, it opens the dropdown but them immediately collapses the problem container. Also, if you click a link, e.g. an image, the problem collapses and then the next page loads.

I'm not sure that this matters but I just thought I'd point it out. This stemmed from #50

**Comment by boonebgorges** [comment]
This should be easy enough to fix. Thanks for the report.

**Comment by moui72** [comment]
oddly, click the dropdown to open it is now fine, but selecting an option still collapses the problem

**Comment by boonebgorges** [comment]
It's looking like I've run out of time to fix this for the October release.

**Comment by boonebgorges** [comment]
I've put an exception in place for `select`, `option`, and `a` elements. I think this should cover embedded images. I'll deploy this shortly to webwork-playground, so please include in your next round of testing.

**Comment by moui72** [comment]
this looks fixed!
