### ISSUE TITLE
Mobile: when filtering for "Show All" problem sets, top dropdown is hidden

### ISSUE THREAD

**Issue by bree-z** [livinglab/webwork-for-wordpress#57]
When I filter for Show All Problem Sets, the dropdown allowing users to sort questions by Most Recent, Most Replies, etc, is partially hidden.  If I choose a particular problem set, it's fine.  

I'm on iOS 10/Safari.

![questionlistdropdown](https://cloud.githubusercontent.com/assets/7189824/18977100/9babd274-8685-11e6-9796-0912317d9d90.jpg)

**Comment by boonebgorges** [comment]
Fix is ready to test.

**Comment by bree-z** [comment]
Looks good, thanks!
