### ISSUE TITLE
"Target" question should be highlighted on problem page

### ISSUE THREAD

**Issue by boonebgorges** [livinglab/webwork-for-wordpress#58]
When clicking a question title from an index, you're led to the corresponding problem page, which then scrolls to the clicked question. We should highlight the clicked question, so that it's still obvious after scrolling around a bit.

Jenna's mockup: https://www.dropbox.com/s/i2sx3dl17u9fofi/OLWW_LAYOUT_PROBLEMPOST_highlight.png?dl=0

**Comment by boonebgorges** [comment]
This is ready to test on openlabdev.org.

Styling doesn't match the mockup exactly. Screenshot:

![screenshot_2016-10-12_09-42-34](https://cloud.githubusercontent.com/assets/246627/19314594/574f583c-9060-11e6-81f6-fa704703b350.png)

The avatar is not flush with the left side. It's not flush with the left margin in *any* question - it's just that it's only noticeable with the yellow background. Should this be addressed, or is it OK as-is?

**Comment by jennaspevack** [comment]
This is fine for now. Thanks Boone!

**Comment by boonebgorges** [comment]
Thank you!
