### ISSUE TITLE
sidebar menu widget inserts home and course profile link

### ISSUE THREAD

**Issue by moui72** [livinglab/webwork-for-wordpress#61]
in the sidebar widget for the menu I created which you can see on the page linked below, the course profile and home link are being inserted. not a huge deal, but ideally I don’t want them there.
http://openlabdev.org/webwork-playground/help/#

**Comment by boonebgorges** [comment]
The Home and Course Profile links are added to every site on the OpenLab by some custom functionality we built years ago. I've just added a flag to the WeBWorK theme that disables them for the OLWW site.

**Comment by boonebgorges** [comment]
Actually, I think this is resolved.
