### ISSUE TITLE
sidebar on help pages not accessible

### ISSUE THREAD

**Issue by moui72** [livinglab/webwork-for-wordpress#62]
the sidebar on help pages is not visible on mobile resolutions. 

is there anyway we can rig it to expand with a click on the magnifying glass the way that the filters do on the question index page? 

i am talking about the sidebar on pages such as the following
http://openlabdev.org/webwork-playground/help/#

**Comment by boonebgorges** [comment]
Sure thing. My apologies for missing this before.

When you say "click on the magnifying glass" I assume you mean "click on the hamburger icon at the left", which is generally the convention for nav menus on mobile. This is what I've implemented on http://openlabdev.org/webwork-playground/

**Comment by moui72** [comment]
this looks good. a minor issue is that the top of the menu is ~3px too far down, showing some of the page behind it. i think it should be flush with the hamburger white margin below the black bar that contains the magnifying glass. if you don't feel like messing with that right now it's fine to leave it until a future update.

![screenshot_20170119-130050](https://cloud.githubusercontent.com/assets/3885628/22119000/d56da48c-de47-11e6-9914-dcb691aa9580.png)

**Comment by boonebgorges** [comment]
Thanks @moui72 - I spent two minutes looking and I couldn't see at a glance where that 3px is coming from in order to make a proper fix. So I did a clunky negative-margin trick instead. Could you confirm that it's addressing the issue?

**Comment by moui72** [comment]
I am not seeing any change :(

**Comment by boonebgorges** [comment]
Did you do a hard refresh? The stylesheets can be quite sticky.

**Comment by bree-z** [comment]
FWIW, I see the same thing as @moui72, on iOS10.2/Safari.

**Comment by boonebgorges** [comment]
Thanks, @bree-z. Since this is quite minor and presumably doesn't affect our current release, and is proving to be non-trivial to solve, I'm going to open a separate ticket for it.

**Comment by moui72** [comment]
thanks all. and yes, i tried everything i could think of to make sure the cache was clear... :man_shrugging: stupid browsers and their stupid caches

**Comment by boonebgorges** [comment]
Thanks to both of you :)
