### ISSUE TITLE
multiline TeX rendering

### ISSUE THREAD

**Issue by drdrew42** [livinglab/webwork-for-wordpress#63]
https://openlab.citytech.cuny.edu/ol-webwork/#/problem/local/3x3-Systems/triangular.pg/question-152

It seems that we're picking up an unforseen "amp;" in this multiline TeX code. (We're also missing the values that follow the equal-sign)

**Comment by moui72** [comment]
can you link to the webwork problem?

**Comment by drdrew42** [comment]
http://mathww.citytech.cuny.edu/webwork2/MAT1275-F16-Parker/3x3-Systems/1/

Use the login I created for boone? 'bgorges'

**Comment by drdrew42** [comment]
There is probably similar issue with the other problems in that set - they use the same TeX code...

**Comment by moui72** [comment]
let's handle this in #84
