### ISSUE TITLE
student version not displaying

### ISSUE THREAD

**Issue by drdrew42** [livinglab/webwork-for-wordpress#64]
I have a student who's saying that their version of a problem is not being displayed.

It seems as though the "show my version" is displaying the version corresponding to the first person to ask this question.

https://openlab.citytech.cuny.edu/ol-webwork/#/problem/local/Circles/identify-center-radical-radius-CtS.pg/question-145

Though it seems to be working correctly elsewhere, where two questions have been asked about the same base-problem.

https://openlab.citytech.cuny.edu/ol-webwork/#/problem/local/Circles/formula-from-diameter-endpts.pg/question-151

**Comment by drdrew42** [comment]
Student told me in class that she asked a question from another student's question page, rather than through the "ask for help" button directly.

**Comment by boonebgorges** [comment]
Aha! Thanks for following up.
