### ISSUE TITLE
Disparity with reply counts

### ISSUE THREAD

**Issue by boonebgorges** [livinglab/webwork-for-wordpress#66]
From @drdrew42:

> Looking on the main page, the top question should be one posed by "Michael Ruiz" (7 days ago) which says there are 2 replies, but there is only one reply to his question. (However, he's asked about this problem twice, and each question has one reply... maybe there's some unintended double-counting?)
> 
> (7 days ago): https://openlab.citytech.cuny.edu/ol-webwork/#/problem/local/Circles/formula-from-diameter-endpts.pg/question-156
> (13 days ago): https://openlab.citytech.cuny.edu/ol-webwork/#/problem/local/Circles/formula-from-diameter-endpts.pg/question-139
>
> and then check their reply counts on the main page."

**Comment by boonebgorges** [comment]
Hi @drdrew42 - I've looked through the existing problems on the site, and I don't see any offenders. (Sorry for not jumping on it right after it was reported.) I also read through the code and I don't see how double-counting would take place - nothing obvious, at least.

**Comment by drdrew42** [comment]
I noticed that the double-counting disappeared not long after I reported the issue. I just figured It got fixed, you should totally take credit.

**Comment by boonebgorges** [comment]
My favorite kind of bug fix!
