### ISSUE TITLE
User should get email notification when someone responds to her question

### ISSUE THREAD

**Issue by boonebgorges** [livinglab/webwork-for-wordpress#68]

**Comment by boonebgorges** [comment]
First pass at this functionality is up. The message sent is as follows (Sally Smith is the person who replied)

Subject:

    [City Tech OpenLab] Sally Smith has replied to your question

Message:

    Sally Smith has replied to your question on City Tech OpenLab.

    To read and reply, visit [question url].

Suggestions on message text are welcome.

Users do not receive notifications when they reply to their own questions.

**Comment by drdrew42** [comment]
Just to clarify, this email is sent to the "owner" of the question?

Overall, the message is straight to the point and I don't think we need much more detail. The subject line is fine, but should the bracketed text mention OpenLab-WeBWorK? Something to distinguish it from other OpenLab emails (does this happen?)

**Comment by boonebgorges** [comment]
> Just to clarify, this email is sent to the "owner" of the question?

Correct - the person who asked the question gets a notification when a response is posted to the question.

> The subject line is fine, but should the bracketed text mention OpenLab-WeBWorK? Something to distinguish it from other OpenLab emails (does this happen?)

Good call. I will make this change.

**Comment by boonebgorges** [comment]
> The subject line is fine, but should the bracketed text mention OpenLab-WeBWorK? Something to distinguish it from other OpenLab emails (does this happen?)

I've made the change.

**Comment by moui72** [comment]
I posted a new question and responded to it, and got an E-mail notification.

I noticed that when I responded to a preexisting question I had posted, there was no notification. Is this intended/does it matter?

Also if I respond to my own question, there is no notification (looking at the commit, this is clearly intended, but I wanted to document it here for future reference)

**Comment by moui72** [comment]
everything looks good otherwise

**Comment by boonebgorges** [comment]
> I noticed that when I responded to a preexisting question I had posted, there was no notification. Is this intended/does it matter?

Is this because the preexisting question was written by the same account as the one you were using to leave a response? Off the top of my head, I can't think of a reason why preexisting questions wouldn't work the same way as new ones.

**Comment by moui72** [comment]
I think it ended up just being very delayed for some reason. Probably nothing to worry about, seems to be working now.

**Comment by boonebgorges** [comment]
Excellent - thank you!
