### ISSUE TITLE
Email notifications of new activity for course instructors

### ISSUE THREAD

**Issue by boonebgorges** [livinglab/webwork-for-wordpress#69]
For spring milestone, we need something like this:

- [x] A hardcoded list that connects instructor OL accounts with section info (as that info is parsed from URLs by WeBWorK
- [x] Someone will have to provide me with that list
- [x] When activity is created, use the list to look up the corresponding instructor, and send an email notification

In the future, we can make this more sophisticated and non-hardcoded

**Comment by drdrew42** [comment]
I'll get you the list for Spring. Just lastnames + email addresses?

**Comment by boonebgorges** [comment]
@drdrew42 I need enough information to match courses to instructors. Email addresses are good on the OL end. I assume last names will work from WW because the last name is always included in the course URL. Is that correct? If so, then yes.

**Comment by drdrew42** [comment]
That's correct. My standard form is "Course###-SemesterYear-LastName"

**Comment by boonebgorges** [comment]
@drdrew42 Ping! Any chance you can provide me with a list, even if it's not complete? Having some real(ish) data - corresponding to a real WW class - will help me to build out the feature. I can always swap out for the up-to-date list closer to the beginning of the term.

**Comment by drdrew42** [comment]
Let me get the list from the seminar team. What data do you need from a real-ish class? You still have access to my Fall16 MAT1275 course on the WW site from last semester - is that enough?

**Comment by boonebgorges** [comment]
I need a list of unique faculty identifiers - I guess this would be 
email addresses, as long as they match the email addresses on file in 
the OpenLab - and the URLs of the WeBWorK courses they're associated with.

**Comment by boonebgorges** [comment]
The basic infrastructure is now in place. The data format that I'll need looks like this:

```
[
  section_name => instructor_email,
  section_name => instructor_email,
]
```

eg

```
[
  'MAT355-TTh434-Gorges' => 'boone@example.com',
  'MAT356-TTh434-Parker-' => 'drew@foo.bar',
]
```

**Comment by moui72** [comment]
this is still waiting on @drdrew42 right?

**Comment by boonebgorges** [comment]
Yes

**Comment by moui72** [comment]
this was ultimately implemented, but needs streamlining for the future. changing milestone

**Comment by boonebgorges** [comment]
A note here (and on #119) that if we get better info from WeBWorK, we may not need this kind of feature. That is, if WW sends us the email(s) of the instructor(s), we can use those to identify corresponding OL users, and skip the course-instructor mapping altogether.

**Comment by boonebgorges** [comment]
This is basically working in its current config, so I'm closing.
