### ISSUE TITLE
Link in sidebar blurb results in 404

### ISSUE THREAD

**Issue by moui72** [livinglab/webwork-for-wordpress#74]
There is a link in the sidebar blurb ("filter"). There is a very hard to notice typo in the href property: the "s" is missing from "question**s**."

```
current:  http://openlabdev.org/webwork-playground/help/explore-existing-question-and-replies/#Filters
intended: http://openlabdev.org/webwork-playground/help/explore-existing-questions-and-replies/#Filters
```
![filters-link](https://cloud.githubusercontent.com/assets/3885628/22305613/2d8ebe8c-e30a-11e6-8d1a-2f2b1453873c.png)

**Comment by moui72** [comment]
See also #60

**Comment by boonebgorges** [comment]
Whoops, sorry about that. Fixed.
