### ISSUE TITLE
very long author name does not wrap appropriately 

### ISSUE THREAD

**Issue by moui72** [livinglab/webwork-for-wordpress#75]
Apologies if you already know about this, but I didn't see an issue for it so I figured I'd document it.

Your super fancy display name on openlabdev.org doesn't wrap as it should. It has a very long string of characters with no spaces which overflows, where I think it should soft-wrap (with hyphen).

![namewrap](https://cloud.githubusercontent.com/assets/3885628/22306161/272a91ae-e30c-11e6-985e-6d88b9fe47db.png)

**Comment by moui72** [comment]
URL to example: http://openlabdev.org/webwork-playground/#/problem/local/GraphingSineCosine/function-graphing.pg/question-11169

Screen shot is from Windows 7, Chrome 55. Looks the same in Windows 7, Firefox 50.

**Comment by boonebgorges** [comment]
Thanks for the ticket. Fixed.
