### ISSUE TITLE
Spring 2017 testing roadbloacks

### ISSUE THREAD

**Issue by moui72** [livinglab/webwork-for-wordpress#76]
A few issues. I think this primarily needs @drdrew42's attention.

1. When logged into webwork using our credentials for the last testing run, “ask for help” button in webwork directs to the production site. This means I can’t create new problems on openlabdev.org/webwork-playground for testing.
2. When logged into webwork using our credentials for the last testing run, I only have access to one course.
3. As a consequence of 1 and 2, only one course and one faculty member appears in the system on openlabdev.org making it so we can't test those filters.

- [x] direct ww-dev "ask for help" button to openlabdev
- [x] create additional course and give access to tpeckenpaugh and bzuckerman
- [x] create additional faculty member(s) (bzuck and tpeck?) for testing the filters

**Comment by moui72** [comment]
@drdrew can you look at issue 2 and 3?

**Comment by drdrew42** [comment]
So, to clarify, we need a second course - and in that course you want two student accounts and two instructor accounts in the new course?

**Comment by moui72** [comment]
Yes please! Or at least one faculty accounts that will show as distinct
from the one attached to the original course, so that we filter questions
by faculty and have more than one choice.

**Comment by drdrew42** [comment]
I believe that filtering by faculty is based on the name of the WeBWorK course? It's not based on the user account in WeBWorK itself. So what should be creating the different entries in the filter menu is differently named courses:

MAT1275-S17-Peck
MAT1275-S17-Zuck

Perhaps something like this?

**Comment by moui72** [comment]
That sounds good. And if it's bothersome to do two you can just do one.
Thanks!

**Comment by moui72** [comment]
@drdrew42 give me a mention when it's ready, if you don't mind -- and let me know how to access a different course if it's non-obvious

thanks again!

**Comment by drdrew42** [comment]
@moui72 and @bree-z 
okay, I've got bzuck:bzuck for [this course](http://mathww.citytech.cuny.edu/MAT9999-S17-Zuck/)
and tpeck:tpeck for [this other course](http://mathww.citytech.cuny.edu/MAT9999-S17-Peck/
)
These courses are not displayed on the WeBWorK mainpage, so you'll have to use these links manually.

**Comment by moui72** [comment]
Thanks! I'm out of testing time tonight but I'll do it tomorrow morning.
Unfortunate we'll miss the release but if there's a problem we'll know
about it and patch ASAP.

**Comment by moui72** [comment]
sorry to bug you again @drdrew42 but these courses don't have the "ask for help" button, and instead have "email my instructor"

can you make the button point to openlabdev.org/webwork-playground like the rainbow course?

**Comment by drdrew42** [comment]
LOL, right. TIL WeBWorK does not copy the course configuration files along with everything else when cloning from the master course. :(

Doing that now.

**Comment by moui72** [comment]
thanks!
