### ISSUE TITLE
Like icon/count only appears as "liked" for user who liked it

### ISSUE THREAD

**Issue by bree-z** [livinglab/webwork-for-wordpress#77]
Here's an example question: http://openlabdev.org/webwork-playground/#/problem/local/AddRationalExpressions/add-DiffSquares-med.pg/question-11276

- While logged in as teststudent I liked the last response in the list for the question above (response was from Test Faculty, "sdas (2x/5)^4 asdasd"). The like icon changed to black and the count changed to 1, as expected.  
- If I log in as tstudent8, I can see that the response moved to the top of the response list, but the like icon/count appears as if there are no likes.  I see the same when not logged in, or if logged in as testfaculty or teststaff.

![1likedresponse_teststudent](https://cloud.githubusercontent.com/assets/7189824/22344111/c35fc7b2-e3c8-11e6-9f79-5ada917d0a77.png)
![2likedresponse_tstudent8](https://cloud.githubusercontent.com/assets/7189824/22344114/c77f12da-e3c8-11e6-9f15-49732e00b1f0.png)

**Comment by moui72** [comment]
I did an additional test: when I liked something as testfaculty, I got the same behavior (reply moved up, but like not shown in count) when viewing from any other account or not logged in.

**Comment by moui72** [comment]
When logged in as super user (account: [supertyler](http://openlabdev.org/members/supertyler/)) my likes are visible to other views

**Comment by boonebgorges** [comment]
Thanks for the details. A quick question about this, as I won't have 
time to dig in in the next couple hours: is the behavior described here 
different from what's currently happening on the production site?

**Comment by moui72** [comment]
it appears to be happening on production also. I liked andrew's response to this question using "teststudent" account:

https://openlab.citytech.cuny.edu/ol-webwork/#/problem/local/TrigonometryRatios/trig-sides-basics.pg/question-161

it is not visible when not logged in or logged in as a different user (e.g. teckenpaugh).

note that this is only for replies -- it appears to work fine for me with questions. is this the case for you as well, @bree-z ?

**Comment by boonebgorges** [comment]
Thanks for the clarification, Tyler - if it's an existing issue, I'll 
probably leave it alone for now (making changes to this sort of thing 
could have unexpected repercussions at this late stage)

**Comment by moui72** [comment]
OK

**Comment by moui72** [comment]
we should assess where we are on this -- @boonebgorges do you need more testing?

**Comment by boonebgorges** [comment]
I think there's enough information for me to try to reproduce. I'll take a look as part of my bugfixing sweep for Fall and will post here if I need more clarification.

**Comment by boonebgorges** [comment]
to be clear: what *ought* to be happening here is:

1. User A likes an item with 0 likes
2. User A now sees a filled-in thumb + a count of 1
3. User B now sees an empty thumb + a count of 1

That is: the count indicates the total number of counts, while the thumb status indicates the current user's like status for the item.

**Comment by boonebgorges** [comment]
related: #72

**Comment by boonebgorges** [comment]
I'm going to close this issue in favor of #72, since I think that the rewrite will automatically cover this.
