### ISSUE TITLE
in-use image was purged

### ISSUE THREAD

**Issue by moui72** [livinglab/webwork-for-wordpress#81]
it looks like we lost an image at some point that is still supposed to display on production

page url
https://openlab.citytech.cuny.edu/ol-webwork/#/problem/local/LawOfSines/geometric-AAS.pg/question-201

image url
http://mathww.citytech.cuny.edu/webwork2_files/tmp/MAT1275-F16-Parker//gif/ae32b78c-ff00-3b18-a5a3-1839f7425e49___317ab538-3c69-3f42-960d-554ee89c6332.png

is this as intended, since the semester ended? do have policy for image expiration date?

**Comment by bree-z** [comment]
In case it's helpful, here's another one:

page url:
https://openlab.citytech.cuny.edu/ol-webwork/#/problem/local/GraphingSineCosine/identify-amplitude.pg/question-176

image:
http://mathww.citytech.cuny.edu/webwork2_files/tmp/MAT1275-F16-Parker//gif/53862018-71c8-38f6-b57d-db236753768d___874be349-0a9e-31f1-962a-74f538106072.png

**Comment by boonebgorges** [comment]
Ping @drdrew42 - I don't know the answer to this one.

**Comment by drdrew42** [comment]
Oh, right. This escaped my prior thinking on this subject - but the course turnover between semesters is going to cause an issue regardless of the image cache flush. 

Between semesters I archive the courses from the previous semester - which removes access to the course. I could keep old courses available, but this means all the old student data will persist in the SQL database. After a few semesters, this would begin to negatively impact WeBWorK's response time. I think this is another argument for archiving any images on the OpenLab side.

**Comment by boonebgorges** [comment]
Thanks for the clarification, @drdrew42. See #39 - I'll be sure to prioritize that for the spring.
