### ISSUE TITLE
E-mail notification: Notify reply authors when their reply is marked as an answer.

### ISSUE THREAD

**Issue by moui72** [livinglab/webwork-for-wordpress#86]
Notify reply authors when their reply is marked as an answer.

**Comment by boonebgorges** [comment]
This is an easy win, and it was indicated by the OL-WW team that it'd be useful to users. Let's do it for Spring 2019.

**Comment by boonebgorges** [comment]
This feature is up and ready to test on openlabdev.org. A screenshot of the email is below. Suggestions welcome about how to make it more helpful.

![screenshot_2018-12-20_15-22-15](https://user-images.githubusercontent.com/246627/50311516-17decd00-046b-11e9-9caa-d4419c5b586d.png)

**Comment by bree-z** [comment]
This looks good, thanks!
