### ISSUE TITLE
Give feedback to users when they submit a question

### ISSUE THREAD

**Issue by moui72** [livinglab/webwork-for-wordpress#87]
Add sentence within form when student submits question, letting them know that they will receive notification when question has been answered (just when question is asked, not for replies)

Andy proposes:
"You will receive an email notification when your question receives a response."

Tyler suggests expanding to:
"Thanks for your question. It has been posted, and you will receive an email notification when your question receives a response."

**Comment by moui72** [comment]
The E-mail notification part is already implemented, this ticket is just about informing the user that they will get E-mail. See #68 .

**Comment by boonebgorges** [comment]
I built the infrastructure for handling something like this, but it's not included in the last round of design mockups, so I can't build the frontend yet. @jspevack - any chance you could let me know whether you think this can be included for this round of development, and if so, how you want the feedback to work?

**Comment by jennaspevack** [comment]
@boonebgorges, sorry! I didn't see this. I can create a quick mockup, no problem. Feedback here is fine.

**Comment by jennaspevack** [comment]
![olww_layout_problempostv5-editquestion](https://user-images.githubusercontent.com/22797200/29096759-00f6e0e8-7c5c-11e7-83c4-e28e0fa2b830.png)

**Comment by boonebgorges** [comment]
Thanks, @jennaspevack! The problem is that we currently scroll to the newly created question after it's posted, so the message wouldn't be easily visible in the place where you've suggested.

**Comment by jennaspevack** [comment]
ah! okay.

**Comment by jennaspevack** [comment]
How about this?

![olww_layout_problempostv5-questionposted](https://user-images.githubusercontent.com/22797200/29128906-cf799206-7cea-11e7-9df2-9c229bc33bcc.png)

**Comment by boonebgorges** [comment]
Cool, I think this should work. Let me see if I'm able to implement in time :)

**Comment by boonebgorges** [comment]
This is done and ready to test.

Previously, after a successful question post, we'd been scrolling to the new question's *response form*. But this was too low to see the feedback. It also doesn't make a ton of sense to me: why would I want to respond to a question I just posted? So I switched it, and now the scroll goes to the newly posted question itself. While testing, could I get a member of the team (maybe @jennaspevack ? ) to approve this change?

**Comment by moui72** [comment]
i like it and it is working! @bree-z what do you think? should we bug jenna?

**Comment by jennaspevack** [comment]
Looks good!

**Comment by boonebgorges** [comment]
Whoop, thanks!
