### ISSUE TITLE
return to top links

### ISSUE THREAD

**Issue by moui72** [livinglab/webwork-for-wordpress#88]
"return to top" should be available throughout the page on desktop views. already there for mobile.

**Comment by boonebgorges** [comment]
See https://www.dropbox.com/s/xqkinpwrfx00ffk/OLWW_LAYOUT_HOMEV5.png?dl=0 for design

**Comment by boonebgorges** [comment]
I've made the changes as per the mockup and they're ready to test on openlabdev.org/webwork-playground.

**Comment by moui72** [comment]
👍  looks good
