### ISSUE TITLE
lazy loading

### ISSUE THREAD

**Issue by moui72** [livinglab/webwork-for-wordpress#89]
Loading speed should be improved with some kind of lazy loading. Infinite scroll (preferred) or click for more.

**Comment by boonebgorges** [comment]
First pass at infinite scroll is now done and ready to test on webwork-playground. Initial load speed and browser performance appear to be much, much improved over the current production site.

The "Loading More..." message at the end of the list - which appears while the AJAX request is in progress - is pretty minimally styled. This is an area for future enhancement.

I've opted to trigger a load-more request only when you reach the last item in the list. This isn't quite as smooth as loading when you hit, say, the third-to-last item. But there are some technical hurdles involved with the latter strategy that I didn't feel like tackling. (Preventing multiple requests, etc.) This is another potential area for future improvement.

Pay special attention when testing to filters and sort orders. They should be respected by the infinite scroll loader. Likewise, changing a filter/sort dropdown should refresh the whole list.

**Comment by moui72** [comment]
I'll try to get some testing in next week

**Comment by bree-z** [comment]
This looks good to me!  I tested on desktop and mobile.  

The only potential issue I see is that the "Top" link is in the site footer, and when the list of problems is very long it's hard to get to the footer.

**Comment by boonebgorges** [comment]
Thanks! Top links will be handled in #88.

**Comment by boonebgorges** [comment]
I'm going to mark this as resolved for the purposes of the milestone. If bugs are discovered during end-to-end testing, please open new tickets with details. Thank you!!
