### ISSUE TITLE
add in-progress question state

### ISSUE THREAD

**Issue by moui72** [livinglab/webwork-for-wordpress#90]
Implement an in-progress state for a question (not answered, but responded to). Jenna to design and decide on separate filter or additional option in the current one.

**Comment by boonebgorges** [comment]
This is ready to test on openlabdev.org/webwork-playground.

I interpreted the sidebar filter options as being mutually exclusive: Even though "In-Progress" items are technically "Unanswered" (in the sense that they don't yet have an accepted answer), the "Unanswered" filter only returns those items that have no responses. Let me know if this feels right.

**Comment by bree-z** [comment]
I've tested, and this looks good to me, i.e. it matches Jenna's comps, and works fine.  Answering a question but not marking as answered changes it to the "In-Progress" label, and the question appears correctly based on filter choices.  

The "Unanswered" filter returning those items that have no responses seems right to me, but I'll let others weigh in.

**Comment by moui72** [comment]
i think the current functionality seems right, and it seems to be working

**Comment by jennaspevack** [comment]
A very small thing :)
The outline/stroke around the response box should be the same color blue as the "In-Progress" header. It's currently the "Answered" blue.

Otherwise, looks good!

**Comment by boonebgorges** [comment]
Thanks, @jennaspevack! This is ready for another test.

**Comment by moui72** [comment]
@bree-z  can I ask you to handle this?

**Comment by jennaspevack** [comment]
thanks @boonebgorges looks good!

**Comment by bree-z** [comment]
will do, @moui72!  i'll take a look tomorrow.

**Comment by bree-z** [comment]
This looks good, thanks!  I'm going to close this one.
