### ISSUE TITLE
threaded comments

### ISSUE THREAD

**Issue by moui72** [livinglab/webwork-for-wordpress#91]
Jonas has seen at least one instance where that would have been useful. But hard to say whether it's a high priority for Fall. Boone thinks it would be a bunch of work. Seems like a lot to add now (in design terms soon). Let's get our faculty buddies' take on this.

**Comment by moui72** [comment]
I think this is on @jspevack's plate for spring?

**Comment by boonebgorges** [comment]
We discussed this in our most recent meeting, and I think there was general consensus that the current schema - one level of responses under each question - fulfills the needs of the project. Let's close this ticket but leave it here for archive purposes.
