### ISSUE TITLE
change post timestamp format

### ISSUE THREAD

**Issue by moui72** [livinglab/webwork-for-wordpress#93]
Perhaps change “posted 19 hours ago” to “posted May 1.” Need input from faculty users.

Jenna: it struck me that the way we formulate the timestamp seems to emphasize how long ago a question was answered. (Also, you can’t actually see the date and time when the action occurred, which seems like a loss of information.)

Charlie: Faculty are a bit sensitive about this - perhaps it can just be a regular timestamp? Let's ask the rest of the team. If needed, let's get this in for Fall.

**Comment by boonebgorges** [comment]
Done and ready to test.

**Comment by bree-z** [comment]
Looks good, thanks!
