### ISSUE TITLE
Collapsed questions should have Replies and Likes graphics

### ISSUE THREAD

**Issue by boonebgorges** [livinglab/webwork-for-wordpress#96]
On Problem view only. See https://www.dropbox.com/s/v1yosvl4yozxwal/OLWW_LAYOUT_PROBLEMPOSTV4-EDITQuestion.png?dl=0

**Comment by boonebgorges** [comment]
This has been implemented and is ready to test.

**Comment by moui72** [comment]
looks good, although I am unsure what you mean by "problem view only" -- the behavior seems to be the same on the filterable index and on the "zoomed in" view

**Comment by boonebgorges** [comment]
"problem view" means "zoomed in". But now that you've mentioned it, I don't know what the design intends. @jspevack can you please chime in?

**Comment by moui72** [comment]
we need to know the intended design for the home/results ("zoomed out") view from @jspevack

**Comment by jennaspevack** [comment]
My understanding is that the design for a collapsed question on any page (home, results, or problem post) would be the same.

**Comment by boonebgorges** [comment]
Gotcha. It looks like it *does* look the same for all collapsed questions, so I think we are good here.
