### ISSUE TITLE
subscription icon sometimes overlaps "like" icon/count

### ISSUE THREAD

**Issue by moui72** [livinglab/webwork-for-wordpress#97]
This was originally noted in #70 and was partially fixed with f7128801b0fb770b4269e93dfd4fb2e9d6589d74

I'm still getting overlapping icons in the following context:

Logged out, zoomed in view, question expanded (not collapsed).

http://openlabdev.org/webwork-playground/#:problemId=local/setGeogebra/circle-center-multians-inc/circle-center-multians-inc.pg:questionId=11445

![screenshot_2017-08-08-11-13-49](https://user-images.githubusercontent.com/3885628/29079457-33f9b41a-7c2b-11e7-8cfb-b420a435b1c6.jpg)

**Comment by moui72** [comment]
fix is likely to be along the lines of `if ( isSingleProblem && ! isCollapsed )` => `if ( userCanPostResponse && isSingleProblem && ! isCollapsed )`

https://github.com/livinglab/webwork-for-wordpress/blob/master/src/components/Question.js#L417

**Comment by boonebgorges** [comment]
Good catch! This should now be resolved.

**Comment by moui72** [comment]
once i convinced my browser that I REALLY wanted new versions of the scripts and that the cached versions were yucky, it indeed appears resolved :)
