### ISSUE TITLE
"In-Progress" question label doesn't change to "Answered"

### ISSUE THREAD

**Issue by bree-z** [livinglab/webwork-for-wordpress#98]
Here's what I did:

* I logged in as Test Student, and asked a question
* Logged in as Test Faculty, I answered that question.  
* Logged in as Test Student, I clicked "This response answered my question." The blue bar on the left side of the reply appears as expected, but the "In-Progress" label at the top doesn't change to "Answered."  When the page is reloaded, the checkbox for "This response answered…" reverts to unchecked.  
* Tested on Firefox, Chrome, and Safari

Question URLs:
http://openlabdev.org/webwork-playground/#:problemId=local/ComplexFractions-Method2/separated-reduce-DoS-med.pg:questionId=11474
http://openlabdev.org/webwork-playground/#:problemId=local/CoordinatePlaneTrig/six-trig-point-q1.pg:questionId=11470

### Question Detail after clicking "This response answered…"

![inprogressnotchanging](https://user-images.githubusercontent.com/7189824/29277842-e651eef2-80e0-11e7-950a-8eeeb2700d65.png)

### Question Detail after page reload

![inprogressafterreload](https://user-images.githubusercontent.com/7189824/29277850-ed6bb3bc-80e0-11e7-9a73-2d29fc59947c.png)

**Comment by bree-z** [comment]
One more update - this appears to a user permissions issue.  I was able to change the question state and have it stick, as an admin, just not as the question author.

**Comment by boonebgorges** [comment]
Thanks for the details, and especially for the user permissions hint. This is almost certainly linked to the change in 977abc88cfe320cc876b6e7613c84972a82bab7f. Marking a question as an "answer" counts as an "edit" from the point of view of the API, which answers the question https://github.com/livinglab/webwork-for-wordpress/issues/31#issuecomment-319783987 of why the original permissions check worked like this.

I'll rearrange to make things more fine-grained.

**Comment by boonebgorges** [comment]
This should be working now - both the permissions issue and the "answered/in-progress" UI issue, which stemmed from the permissions problem.

**Comment by bree-z** [comment]
This looks good, thanks!
